import { createHash } from 'node:crypto'

import { AI_PROMPT_VERSION, type AssistantContextPack, type VisualBrief } from '@zenui/ai-core'
import { DEPLOYMENT_CONTENT_TYPE } from '@zenui/deployment-core'
import { createRemoteImagePolicy, createValidDesignFixture, migrateDesignDocumentV1ToV2 } from '@zenui/design-schema'
import { describe, expect, it, vi } from 'vitest'

import {
  createDeploymentProcessor,
  createExportProcessor,
  createDesignDirectionProcessor,
  createGenerationProcessor,
  createMediaProposalV2Resolver,
  createGeminiImageGenerator,
  createGeminiProvider,
  createGeminiMediaIntelligenceProvider,
  createHybridMediaResolver,
  createLayoutProposalV2Resolver,
  createSectionCompositionV2Resolver,
  createStyleProposalV2Resolver,
  createMockWorkerProvider,
  workerBoundary,
} from '../src/index.js'

const job = {
  generationRunId: '11111111-1111-4111-8111-111111111111',
  projectId: '22222222-2222-4222-8222-222222222222',
  workspaceId: '33333333-3333-4333-8333-333333333333',
  userId: '44444444-4444-4444-8444-444444444444',
  mode: 'generate' as const,
  prompt: 'Create a launch landing page',
  expectedVersion: 1,
}

const context = { userId: job.userId, workspaceId: job.workspaceId }

const blueprint = {
  version: 1 as const,
  brand: 'ZenUI',
  theme: {
    primary: '#2563eb', background: '#ffffff', text: '#0f172a',
    headingFont: 'Manrope' as const, bodyFont: 'Manrope' as const,
  },
  hero: {
    heading: 'Generated by worker', paragraph: 'A safe structured page.',
    cta: { text: 'Get started', href: '#start' },
  },
  features: [
    { icon: 'star' as const, heading: 'Fast', paragraph: 'Generate focused content.' },
    { icon: 'check' as const, heading: 'Safe', paragraph: 'Keep structure server-owned.' },
  ],
}

describe('AI worker boundary', () => {
  it('never executes user code', () => {
    expect(workerBoundary).toEqual({
      responsibilities: ['ai-generation', 'asset-processing', 'export', 'deployment'],
      executesUserCode: false,
    })
  })

  it('maps Gemini structured output and usage without exposing the SDK response', async () => {
    const generateContent = vi.fn().mockResolvedValue({
      text: JSON.stringify(blueprint),
      usageMetadata: { promptTokenCount: 10, candidatesTokenCount: 20, totalTokenCount: 30 },
    })
    const provider = createGeminiProvider({
      model: 'gemini-test',
      generateContent,
    })

    const result = await provider.generateLandingPageBlueprint({
      promptVersion: AI_PROMPT_VERSION,
      prompt: 'Build safely',
      context: { mode: 'generate', request: 'Build safely', registry: [], theme: createValidDesignFixture().theme },
      signal: new AbortController().signal,
    })

    expect(result).toEqual({
      output: blueprint,
      usage: { inputTokens: 10, outputTokens: 20, totalTokens: 30 },
    })
    expect(generateContent).toHaveBeenCalledWith(expect.objectContaining({
      model: 'gemini-test',
      config: expect.objectContaining({
        responseMimeType: 'application/json',
        responseJsonSchema: expect.objectContaining({
          properties: expect.objectContaining({
            version: expect.any(Object), pagePreset: expect.any(Object), themePreset: expect.any(Object),
            navbarVariant: expect.any(Object), heroVariant: expect.any(Object), sectionOrder: expect.any(Object),
            heroHeading: expect.any(Object), features: expect.any(Object),
          }),
        }),
      }),
    }), expect.any(AbortSignal))
    expect(generateContent.mock.calls[0]?.[0].config).not.toHaveProperty('abortSignal')
    expect(generateContent.mock.calls[0]?.[0].config).not.toHaveProperty('httpOptions')
    const contents = JSON.parse(generateContent.mock.calls[0]?.[0].contents) as {
      outputContract: string
      compositionGuidance: string
    }
    expect(contents.outputContract).toContain('landing-page blueprint')
    expect(contents.compositionGuidance).toContain('Blueprint version 2')
    expect(contents.compositionGuidance).toContain('footer must be last')
    const projectedSchema = JSON.stringify(generateContent.mock.calls[0]?.[0].config.responseJsonSchema)
    expect(projectedSchema).not.toMatch(/projectId|parentId|children|nodes|pages/)
    expect(projectedSchema).not.toContain('"oneOf"')
    expect(projectedSchema).not.toContain('"anyOf"')
    expect(projectedSchema).toContain('"sectionOrder"')
    expect(projectedSchema).toContain('"logos"')
    expect(projectedSchema).toContain('"footerTagline"')
    expect(JSON.stringify(generateContent.mock.calls[0]?.[0])).not.toContain('additionalProperties')
    expect(JSON.stringify(generateContent.mock.calls[0]?.[0]).length).toBeLessThan(50_000)
  })

  it('uses zero token fallbacks and bounded image-host guidance for sparse Gemini responses', async () => {
    const generateContent = vi.fn().mockResolvedValue({ text: JSON.stringify(blueprint) })
    const provider = createGeminiProvider({ model: 'gemini-test', generateContent })
    const result = await provider.generateLandingPageBlueprint({
      promptVersion: AI_PROMPT_VERSION,
      prompt: 'Build with approved images',
      context: {
        mode: 'generate', request: 'Build with approved images', registry: [],
        theme: createValidDesignFixture().theme,
        imageHosts: ['images.example.com'],
      },
      signal: new AbortController().signal,
    })
    expect(result.usage).toEqual({ inputTokens: 0, outputTokens: 0, totalTokens: 0 })
    const contents = JSON.parse(generateContent.mock.calls[0]?.[0].contents) as { imageGuidance?: string }
    expect(contents.imageGuidance).toContain('images.example.com')

    const missingText = createGeminiProvider({
      model: 'gemini-test', generateContent: vi.fn().mockResolvedValue({ text: undefined }),
    })
    await expect(missingText.generateLandingPageBlueprint({
      promptVersion: AI_PROMPT_VERSION, prompt: 'Build',
      context: { mode: 'generate', request: 'Build', registry: [], theme: createValidDesignFixture().theme },
      signal: new AbortController().signal,
    })).rejects.toMatchObject({ code: 'provider_error' })
  })

  it('generates one transient direction set with exactly one Gemini request and no document apply', async () => {
    const brief = {
      description: 'NovaFlow helps small product teams plan launches.',
      offer: 'A guided launch planning workspace',
      audience: 'Small product teams preparing their first launch',
      primaryGoal: 'Collect qualified consultation requests',
      cta: 'Book a consultation',
      tone: 'Clear, confident, and modern',
      brandDetails: '',
      mustHaveSections: ['introduction', 'benefits', 'trust', 'faq', 'contact'],
    } as const
    const contentBlueprint = {
      version: 1 as const,
      language: 'en' as const,
      pagePreset: 'saas' as const,
      brand: 'NovaFlow',
      announcement: 'Plan product launches with clarity',
      navLabels: ['Benefits', 'Results', 'Questions'],
      heroBadge: 'For small product teams',
      heroHeading: 'Plan every product launch with clarity',
      heroParagraph: 'Keep goals, decisions, and milestones in one shared plan.',
      heroSecondaryCta: 'See how it works',
      heroProof: 'One shared path from idea to launch day',
      heroImage: {
        query: 'product team planning launch workspace',
        alt: 'Product team planning a launch together',
      },
      contentImages: [
        { slot: 'feature-1' as const, query: 'product launch roadmap board', alt: 'Product launch roadmap board' },
        { slot: 'feature-2' as const, query: 'team reviewing launch milestones', alt: 'Team reviewing launch milestones' },
        { slot: 'feature-3' as const, query: 'collaborative launch handoff', alt: 'Collaborative product launch handoff' },
      ],
      logos: ['Acme', 'Orbit', 'Luma'],
      statsHeading: 'Momentum your team can see',
      stats: [{ value: '1', label: 'shared plan' }, { value: '24/7', label: 'available context' }, { value: '5', label: 'clear steps' }],
      featuresHeading: 'Replace scattered work with shared momentum',
      featuresParagraph: 'NovaFlow keeps every important decision in one clear story.',
      features: [
        { icon: 'check' as const, heading: 'One launch story', paragraph: 'Keep goals and milestones in one understandable plan.' },
        { icon: 'star' as const, heading: 'Clear next steps', paragraph: 'Know what needs attention next.' },
        { icon: 'arrow-right' as const, heading: 'Confident handoffs', paragraph: 'Give every teammate enough context.' },
      ],
      testimonialsHeading: 'A plan the whole team can follow',
      testimonials: [
        { quote: 'Our whole team finally sees one shared plan.', name: 'Linh Nguyen', role: 'Product lead' },
        { quote: 'We spend less time asking for status.', name: 'Minh Tran', role: 'Founder' },
      ],
      pricingHeading: 'Choose the right way to start',
      pricingParagraph: 'Start small and grow when the team is ready.',
      plans: [
        { name: 'Starter', price: 'Free', description: 'For a first launch.', features: ['One plan', 'Core guidance'], highlighted: false },
        { name: 'Growth', price: '$19/month', description: 'For growing teams.', features: ['Unlimited plans', 'Priority support'], highlighted: true },
      ],
      faqHeading: 'What to know before you begin',
      faqs: [
        { question: 'Can we start with one launch?', answer: 'Yes. Start with one active launch.' },
        { question: 'Does the team need training?', answer: 'No. Every step is clearly guided.' },
        { question: 'Can we keep our process?', answer: 'Yes. Keep what works and simplify the rest.' },
      ],
      finalCtaHeading: 'Give your next launch a clear path',
      finalCtaParagraph: 'Start with a plan the entire team can trust.',
      footerTagline: 'Guided launch planning for focused teams.',
      copyright: '© 2026 NovaFlow.',
      sectionOrder: ['logo-cloud', 'stats', 'features', 'testimonials', 'faq', 'final-cta', 'footer'],
    }
    const generateContent = vi.fn().mockResolvedValue({
      text: JSON.stringify(contentBlueprint),
      usageMetadata: { promptTokenCount: 20, candidatesTokenCount: 30, totalTokenCount: 50 },
    })
    const provider = createGeminiProvider({ model: 'gemini-test', generateContent })
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: job.generationRunId,
        projectId: job.projectId,
        workspaceId: job.workspaceId,
        createdBy: job.userId,
        expectedVersion: 1,
        round: 0,
        brief,
        document: createValidDesignFixture(),
      }),
      claim: vi.fn().mockResolvedValue({ status: 'running' }),
      complete: vi.fn().mockResolvedValue({ accepted: true, run: { status: 'completed' } }),
      fail: vi.fn(),
    }
    const resolveMedia = vi.fn().mockImplementation(({ intent }: { intent: { slot: string; alt: string } }) => Promise.resolve({
      assetId: ({
        hero: '55555555-5555-4555-8555-555555555555',
        'feature-1': '66666666-6666-4666-8666-666666666666',
        'feature-2': '77777777-7777-4777-8777-777777777777',
        'feature-3': '88888888-8888-4888-8888-888888888888',
      } as Record<string, string>)[intent.slot],
      alt: intent.alt,
      decorative: false as const,
    }))
    const processor = createDesignDirectionProcessor({ provider, repository, resolveMedia })

    await expect(processor({ data: {
      designDirectionRunId: job.generationRunId,
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      userId: job.userId,
    } })).resolves.toMatchObject({ status: 'completed' })
    expect(generateContent).toHaveBeenCalledOnce()
    expect(resolveMedia).toHaveBeenCalledTimes(4)
    expect(resolveMedia.mock.calls.map(call => (call[0] as { intent: { slot: string } }).intent.slot)).toEqual([
      'hero', 'feature-1', 'feature-2', 'feature-3',
    ])
    expect(resolveMedia).toHaveBeenCalledWith(expect.objectContaining({
      context,
      projectId: job.projectId,
      runId: job.generationRunId,
      intent: { slot: 'hero', ...contentBlueprint.heroImage },
    }))
    expect(repository.complete).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      blueprint: contentBlueprint,
      directions: expect.arrayContaining([expect.objectContaining({
        document: expect.objectContaining({
          nodes: expect.objectContaining({
            'hero-image': expect.objectContaining({
              props: {
                assetId: '55555555-5555-4555-8555-555555555555',
                alt: 'Product team planning a launch together',
                decorative: false,
              },
            }),
          }),
        }),
      })]),
      usage: { inputTokens: 20, outputTokens: 30, totalTokens: 50 },
    }))
    const providerRequest = JSON.parse(generateContent.mock.calls[0]?.[0].contents) as { outputContract: string }
    expect(providerRequest.outputContract).toContain('image search intent')
    expect(JSON.stringify(generateContent.mock.calls[0]?.[0])).not.toMatch(/providerResultId|assetId/i)
  })

  it('uses enforced Gemini schemas for visual briefs and batch candidate judgments', async () => {
    const visualBrief: VisualBrief = {
      version: 'visual-brief-v1', subject: 'Product development workflow', message: 'Five stages',
      representation: 'process-diagram', composition: 'Five columns linked by arrows',
      mustInclude: ['five stages', 'arrows'], mustAvoid: ['people'], peoplePolicy: 'forbidden',
      textPolicy: 'symbolic-only', style: 'editorial diagram', palette: ['#2563eb'],
      aspectRatio: 'wide', focalArea: 'center',
      generationPrompt: 'Five stage product process diagram without people or readable text',
      searchQuery: null, alt: 'Five-stage product development process diagram',
    }
    const evaluations = [{
      candidateId: 'candidate-0', semanticRelevance: 0.9, representationMatch: 0.95,
      mustIncludeCoverage: 0.9, compositionFit: 0.85, websiteUsability: 0.88,
      confidence: 0.9, violations: [], safeReason: 'Matches the process brief.',
    }]
    const generateContent = vi.fn()
      .mockResolvedValueOnce({
        text: JSON.stringify(visualBrief),
        usageMetadata: { promptTokenCount: 10, candidatesTokenCount: 20, totalTokenCount: 30 },
      })
      .mockResolvedValueOnce({
        text: JSON.stringify(evaluations),
        usageMetadata: { promptTokenCount: 5, candidatesTokenCount: 7, totalTokenCount: 12 },
      })
    const provider = createGeminiMediaIntelligenceProvider({ model: 'gemini-test', generateContent })
    const contextPack: AssistantContextPack = {
      version: 'assistant-context-v1', request: 'Create a five-step process board without people', locale: 'en',
      documentVersion: 1, scope: { kind: 'element', rootNodeId: 'image-1', sectionNodeId: 'section-1' },
      selectedNode: { id: 'image-1', type: 'image', props: { alt: 'Current image' } },
      section: { id: 'section-1', type: 'section', label: 'Features', text: 'Product workflow' },
      surroundings: [], websiteBrief: null, theme: createValidDesignFixture().theme,
      mediaSlot: { kind: 'image', aspectRatio: 'wide', alt: 'Current image' },
    }

    await expect(provider.planVisualBrief({ context: contextPack, signal: new AbortController().signal })).resolves.toEqual({
      output: visualBrief, usage: { inputTokens: 10, outputTokens: 20, totalTokens: 30 },
    })
    await expect(provider.evaluateBatch({
      brief: visualBrief,
      candidates: [{ candidateId: 'candidate-0', source: 'generated', bytes: new Uint8Array([1, 2, 3]) }],
      signal: new AbortController().signal,
    })).resolves.toEqual({ output: evaluations, usage: { inputTokens: 5, outputTokens: 7, totalTokens: 12 } })
    expect(generateContent).toHaveBeenCalledTimes(2)
    expect(generateContent.mock.calls[0]?.[0].config).toMatchObject({
      responseMimeType: 'application/json', responseJsonSchema: expect.objectContaining({ type: 'object' }),
    })
    expect(generateContent.mock.calls[1]?.[0].contents).toEqual(expect.arrayContaining([
      expect.objectContaining({ inlineData: { mimeType: 'image/webp', data: Buffer.from([1, 2, 3]).toString('base64') } }),
    ]))
    expect(JSON.stringify(generateContent.mock.calls)).not.toMatch(/assetId|objectKey|providerResultId/)
  })

  it('uses the enforced semantic style schema without exposing raw style values', async () => {
    const styleSpec = {
      version: 'style-edit-spec-v1', emphasis: 'strong', spacingDensity: 'comfortable',
      alignment: 'center', surface: 'none', mobileStack: 'preserve',
    }
    const generateContent = vi.fn().mockResolvedValue({
      text: JSON.stringify(styleSpec),
      usageMetadata: { promptTokenCount: 3, candidatesTokenCount: 4, totalTokenCount: 7 },
    })
    const provider = createGeminiMediaIntelligenceProvider({ model: 'gemini-test', generateContent })
    const contextPack: AssistantContextPack = {
      version: 'assistant-context-v1', request: 'Center and emphasize this heading', locale: 'en',
      documentVersion: 1, scope: { kind: 'element', rootNodeId: 'heading-1', sectionNodeId: 'section-1' },
      selectedNode: { id: 'heading-1', type: 'heading', props: { text: 'Heading' } },
      section: { id: 'section-1', type: 'section', label: 'Features', text: 'Heading' },
      surroundings: [], websiteBrief: null, theme: createValidDesignFixture().theme, mediaSlot: null,
    }

    await expect(provider.planStyleEdit({
      context: contextPack, signal: new AbortController().signal,
    })).resolves.toEqual({
      output: styleSpec, usage: { inputTokens: 3, outputTokens: 4, totalTokens: 7 },
    })
    expect(generateContent.mock.calls[0]?.[0].config.responseJsonSchema).toMatchObject({
      type: 'object', properties: {
        emphasis: expect.objectContaining({ enum: ['preserve', 'subtle', 'strong'] }),
      },
    })
    expect(JSON.stringify(generateContent.mock.calls[0]?.[0])).not.toMatch(/rawCss|backgroundColor|fontFamily|https?:/)
  })

  it('generates bounded image bytes through Gemini generateContent and falls back to Pexels on safe failure', async () => {
    const generateContent = vi.fn().mockResolvedValue({
      candidates: [{ content: { parts: [{ inlineData: {
        data: Buffer.from('generated-image').toString('base64'), mimeType: 'image/png',
      } }] } }],
    })
    const generator = createGeminiImageGenerator({ model: 'gemini-image-test', generateContent })
    await expect(generator.generate({
      prompt: 'Editorial product team planning launch milestones, no text or logos',
      aspectRatio: '16:9',
      signal: new AbortController().signal,
    })).resolves.toEqual({
      bytes: new Uint8Array(Buffer.from('generated-image')),
      mimeType: 'image/png',
      provider: 'google',
      model: 'gemini-image-test',
    })
    expect(generateContent).toHaveBeenCalledWith({
      model: 'gemini-image-test',
      contents: 'Editorial product team planning launch milestones, no text or logos',
      config: {
        responseModalities: ['IMAGE'],
        imageConfig: { aspectRatio: '16:9', imageSize: '1K' },
      },
    }, expect.any(AbortSignal))
    expect(JSON.stringify(generateContent.mock.calls[0]?.[0])).not.toMatch(/numberOfImages|addWatermark|enhancePrompt/)

    const generated = vi.fn().mockRejectedValue(Object.assign(new Error('safety detail'), { code: 'image_safety' }))
    const pexels = vi.fn().mockResolvedValue({ assetId: '55555555-5555-4555-8555-555555555555', alt: 'Fallback', decorative: false })
    const resolver = createHybridMediaResolver({ generateOwned: generated, resolvePexels: pexels })
    await expect(resolver({ slot: 'hero', query: 'product team planning', alt: 'Fallback' })).resolves.toMatchObject({
      assetId: '55555555-5555-4555-8555-555555555555',
    })
    expect(generated).toHaveBeenCalledOnce()
    expect(pexels).toHaveBeenCalledOnce()

    generated.mockResolvedValueOnce({ assetId: '66666666-6666-4666-8666-666666666666', alt: 'Generated', decorative: false })
    await expect(resolver({ slot: 'feature-1', query: 'launch roadmap', alt: 'Generated' })).resolves.toMatchObject({
      assetId: '66666666-6666-4666-8666-666666666666',
    })
    expect(pexels).toHaveBeenCalledOnce()
  })

  it('rejects Gemini image responses without exactly one supported inline image', async () => {
    for (const response of [
      { candidates: [] },
      { candidates: [{ content: { parts: [{ text: 'No image available' }] } }] },
      { candidates: [{ content: { parts: [{ inlineData: { data: 'aW1hZ2U=', mimeType: 'image/gif' } }] } }] },
      { candidates: [{ content: { parts: [{ inlineData: { data: undefined, mimeType: 'image/png' } }] } }] },
      { candidates: [{ content: { parts: [
        { inlineData: { data: 'aW1hZ2U=', mimeType: 'image/png' } },
        { inlineData: { data: 'aW1hZ2U=', mimeType: 'image/png' } },
      ] } }] },
    ]) {
      const generator = createGeminiImageGenerator({
        model: 'gemini-image-test',
        generateContent: vi.fn().mockResolvedValue(response),
      })
      await expect(generator.generate({
        prompt: 'A bounded website image', aspectRatio: '4:3', signal: new AbortController().signal,
      })).rejects.toMatchObject({ code: 'image_invalid' })
    }
  })

  it('normalizes malformed JSON and provider errors to safe codes', async () => {
    const malformed = createGeminiProvider({
      model: 'gemini-test',
      generateContent: vi.fn().mockResolvedValue({ text: '{bad json' }),
    })
    await expect(malformed.generateLandingPageBlueprint({
      promptVersion: AI_PROMPT_VERSION, prompt: 'Build',
      context: { mode: 'generate', request: 'Build', registry: [], theme: createValidDesignFixture().theme },
      signal: new AbortController().signal,
    })).rejects.toMatchObject({ code: 'provider_error' })

    const denied = createGeminiProvider({
      model: 'gemini-test',
      generateContent: vi.fn().mockRejectedValue(Object.assign(new Error('API key leaked-provider-detail'), { status: 401 })),
    })
    await expect(denied.generateLandingPageBlueprint({
      promptVersion: AI_PROMPT_VERSION, prompt: 'Build',
      context: { mode: 'generate', request: 'Build', registry: [], theme: createValidDesignFixture().theme },
      signal: new AbortController().signal,
    })).rejects.toMatchObject({ code: 'provider_auth', message: 'provider_auth' })

    for (const [error, code] of [
      [Object.assign(new Error('limited'), { status: 429 }), 'provider_rate_limit'],
      [Object.assign(new Error('unavailable'), { status: 503 }), 'provider_transient'],
      [Object.assign(new Error('aborted'), { name: 'AbortError' }), 'provider_timeout'],
    ] as const) {
      const failed = createGeminiProvider({
        model: 'gemini-test',
        generateContent: vi.fn().mockRejectedValue(error),
      })
      await expect(failed.generateLandingPageBlueprint({
        promptVersion: AI_PROMPT_VERSION, prompt: 'Build',
        context: { mode: 'generate', request: 'Build', registry: [], theme: createValidDesignFixture().theme },
        signal: new AbortController().signal,
      })).rejects.toMatchObject({ code, message: code })
    }
  })

  it('maps Gemini bad requests to a distinct safe failure code', async () => {
    const failed = createGeminiProvider({
      model: 'gemini-test',
      generateContent: vi.fn().mockRejectedValue(Object.assign(new Error('provider detail'), { status: 400 })),
    })
    await expect(failed.generateOperations({
      promptVersion: AI_PROMPT_VERSION, prompt: 'Shorten heading',
      context: { mode: 'edit-selection', request: 'Shorten heading', registry: [], theme: createValidDesignFixture().theme },
      signal: new AbortController().signal,
    })).rejects.toMatchObject({ code: 'provider_bad_request', message: 'provider_bad_request' })
  })

  it('projects selection edits to a Gemini-compatible copy schema', async () => {
    const generateContent = vi.fn().mockResolvedValue({
      text: JSON.stringify({ summary: 'Shortened Hero heading', updates: [{
        nodeId: 'hero-heading', property: 'text', value: 'AI chăm sóc khách hàng hiệu quả hơn',
      }] }),
      usageMetadata: { promptTokenCount: 4, candidatesTokenCount: 6, totalTokenCount: 10 },
    })
    const provider = createGeminiProvider({ model: 'gemini-test', generateContent })
    const document = createValidDesignFixture()
    document.nodes['hero-1'] = {
      id: 'hero-1', type: 'hero', parentId: 'page-root', children: ['hero-heading'],
      props: { label: 'Hero' }, style: {}, responsive: {},
    }
    document.nodes['hero-heading'] = {
      id: 'hero-heading', type: 'heading', parentId: 'hero-1', children: [],
      props: { text: 'Tự động hóa quy trình chăm sóc khách hàng với sức mạnh AI', level: 1 }, style: {}, responsive: {},
    }

    const result = await provider.generateOperations({
      promptVersion: AI_PROMPT_VERSION,
      prompt: 'Đổi tiêu đề Hero ngắn gọn hơn',
      context: {
        mode: 'edit-selection', request: 'Đổi tiêu đề Hero ngắn gọn hơn', registry: [], theme: document.theme,
        selectedNodeId: 'hero-1', selectedNodes: {
          'hero-1': document.nodes['hero-1'], 'hero-heading': document.nodes['hero-heading'],
        }, editableProps: { 'hero-heading': ['text', 'level'] },
        editIntent: 'copy',
      },
      signal: new AbortController().signal,
    })

    expect(result.output).toEqual({
      summary: 'Shortened Hero heading',
      operations: [{
        type: 'UPDATE_PROPS', nodeId: 'hero-heading', patch: { text: 'AI chăm sóc khách hàng hiệu quả hơn' },
      }],
    })
    const schema = JSON.stringify(generateContent.mock.calls[0]?.[0].config.responseJsonSchema)
    expect(schema.length).toBeLessThan(8_000)
    expect(schema).not.toContain('oneOf')
    expect(schema).not.toContain('anyOf')
    expect(schema).not.toContain('INSERT_NODE')
    expect(schema).not.toContain('UPDATE_PROPS')
    expect(schema).not.toContain('hero-heading')
    expect(schema).toContain('updates')
    expect(schema).toContain('property')
    const contents = JSON.parse(generateContent.mock.calls[0]?.[0].contents) as { editGuidance?: string }
    expect(contents.editGuidance).toContain('fewest operations')
  })

  it('uses fallback usage counts and the static edit schema for edit requests', async () => {
    const generateContent = vi.fn().mockResolvedValue({
      text: JSON.stringify({
        summary: 'Edit', updates: [{ nodeId: 'heading-1', property: 'text', value: 'Edited' }],
      }),
      usageMetadata: { promptTokenCount: 4, candidatesTokenCount: 6 },
    })
    const provider = createGeminiProvider({ model: 'gemini-test', generateContent, editMaxOutputTokens: 1024 })
    const result = await provider.generateOperations({
      promptVersion: AI_PROMPT_VERSION, prompt: 'Edit',
      context: {
        mode: 'edit-page', request: 'Edit', registry: [], theme: createValidDesignFixture().theme,
        document: createValidDesignFixture(), editableProps: { 'heading-1': ['text', 'level'] }, editIntent: 'copy',
      },
      repair: { attempt: 1, issues: ['invalid output'] },
      signal: new AbortController().signal,
    })

    expect(result).toMatchObject({
      output: {
        summary: 'Edit', operations: [{ type: 'UPDATE_PROPS', nodeId: 'heading-1', patch: { text: 'Edited' } }],
      },
      usage: { inputTokens: 4, outputTokens: 6, totalTokens: 10 },
    })
    expect(generateContent).toHaveBeenCalledWith(expect.objectContaining({
      config: expect.objectContaining({ maxOutputTokens: 1024, responseMimeType: 'application/json' }),
    }), expect.any(AbortSignal))
    expect(generateContent.mock.calls[0]?.[0].config.responseJsonSchema).toMatchObject({
      properties: { summary: expect.any(Object), updates: expect.any(Object) },
    })
    expect(JSON.parse(generateContent.mock.calls[0]?.[0].contents)).toMatchObject({
      outputContract: expect.stringContaining('operation batch'),
    })
  })

  it('compiles and uploads one deterministic multi-route ZIP without executing user code', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: '55555555-5555-4555-8555-555555555555',
        projectId: job.projectId,
        workspaceId: job.workspaceId,
        createdBy: job.userId,
        document: (() => {
          const document = migrateDesignDocumentV1ToV2(createValidDesignFixture())
          document.nodes['about-root'] = { id: 'about-root', type: 'page', parentId: null, children: [], props: {}, style: {}, responsive: {} }
          document.pages.push({ id: 'about', name: 'About', slug: '/about', rootNodeId: 'about-root' })
          return document
        })(),
      }),
      claim: vi.fn().mockResolvedValue({ status: 'running' }),
      complete: vi.fn().mockResolvedValue({ status: 'completed' }),
      fail: vi.fn(),
    }
    const store = { put: vi.fn().mockResolvedValue(undefined), get: vi.fn() }
    const processor = createExportProcessor({ repository, store, maxArtifactBytes: 2 * 1024 * 1024 })
    const exportJob = {
      exportRunId: '55555555-5555-4555-8555-555555555555',
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      userId: job.userId,
    }

    await expect(processor({ data: exportJob })).resolves.toMatchObject({ status: 'completed' })
    expect(store.put).toHaveBeenCalledWith(expect.objectContaining({
      key: `exports/${job.workspaceId}/${job.projectId}/${exportJob.exportRunId}/site.zip`,
      contentType: 'application/zip',
      checksum: expect.stringMatching(/^[a-f0-9]{64}$/),
      content: expect.any(Uint8Array),
    }))
    const uploaded = store.put.mock.calls[0]?.[0] as { content: Uint8Array } | undefined
    expect(uploaded?.content.slice(0, 4)).toEqual(Uint8Array.from([0x50, 0x4b, 0x03, 0x04]))
    expect(repository.complete).toHaveBeenCalledWith(expect.any(Object), exportJob.exportRunId, expect.objectContaining({
      artifactKey: expect.stringContaining(exportJob.exportRunId),
      bytes: expect.any(Number),
      routeCount: 2,
    }))
  })

  it('bundles integrity-checked owned assets into portable export artifacts', async () => {
    const assetId = '66666666-6666-4666-8666-666666666666'
    const bytes = Uint8Array.from([0x52, 0x49, 0x46, 0x46])
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = { assetId, alt: 'Product dashboard', decorative: false }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: '55555555-5555-4555-8555-555555555555', projectId: job.projectId,
        workspaceId: job.workspaceId, createdBy: job.userId, document,
      }),
      getPublicationAssets: vi.fn().mockResolvedValue([{
        id: assetId, objectKey: `private/${assetId}/image.webp`, contentType: 'image/webp', bytes: bytes.byteLength,
        checksum: createHash('sha256').update(bytes).digest('hex'),
      }]),
      claim: vi.fn().mockResolvedValue({ status: 'running' }),
      complete: vi.fn().mockResolvedValue({ status: 'completed' }),
      fail: vi.fn(),
    }
    const assetStore = { get: vi.fn().mockResolvedValue(bytes) }
    const store = { put: vi.fn().mockResolvedValue(undefined), get: vi.fn() }
    const processor = createExportProcessor({ repository, store, assetStore })

    await expect(processor({ data: {
      exportRunId: '55555555-5555-4555-8555-555555555555', projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'completed' })
    const uploaded = store.put.mock.calls[0]?.[0] as { content: Uint8Array } | undefined
    const archive = new TextDecoder().decode(uploaded?.content)
    expect(repository.getPublicationAssets).toHaveBeenCalledWith(context, job.projectId, [assetId])
    expect(assetStore.get).toHaveBeenCalledWith(`private/${assetId}/image.webp`)
    expect(archive).toContain(`assets/${assetId}.webp`)
    expect(archive).toContain(`src="assets/${assetId}.webp"`)
    expect(archive).toContain("img-src 'self'")
    expect(archive).not.toMatch(/localhost|127\.0\.0\.1|private\//)
  })

  it('fails portable export when an owned asset is corrupt before artifact storage', async () => {
    const assetId = '66666666-6666-4666-8666-666666666666'
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = { assetId, alt: 'Product dashboard', decorative: false }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: '55555555-5555-4555-8555-555555555555', projectId: job.projectId,
        workspaceId: job.workspaceId, createdBy: job.userId, document,
      }),
      getPublicationAssets: vi.fn().mockResolvedValue([{
        id: assetId, objectKey: 'private/image.webp', contentType: 'image/webp', bytes: 4, checksum: 'a'.repeat(64),
      }]),
      claim: vi.fn().mockResolvedValue({ status: 'running' }),
      complete: vi.fn(),
      fail: vi.fn().mockResolvedValue({ status: 'failed' }),
    }
    const store = { put: vi.fn(), get: vi.fn() }
    const processor = createExportProcessor({
      repository, store, assetStore: { get: vi.fn().mockResolvedValue(Uint8Array.from([1, 2, 3, 4])) },
    })

    await expect(processor({ data: {
      exportRunId: '55555555-5555-4555-8555-555555555555', projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'failed' })
    expect(store.put).not.toHaveBeenCalled()
    expect(repository.fail).toHaveBeenCalledWith(context, expect.any(String), 'invalid_document')
  })

  it('rejects export images outside the shared policy before storage', async () => {
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = { src: 'https://evil.example.test/hero.png', alt: 'Denied' }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: '55555555-5555-4555-8555-555555555555', projectId: job.projectId,
        workspaceId: job.workspaceId, createdBy: job.userId, document,
      }),
      claim: vi.fn().mockResolvedValue({ status: 'running' }),
      complete: vi.fn(),
      fail: vi.fn().mockResolvedValue({ status: 'failed' }),
    }
    const store = { put: vi.fn(), get: vi.fn() }
    const processor = createExportProcessor({
      repository, store, imagePolicy: createRemoteImagePolicy('images.example.com'),
    })
    await expect(processor({ data: {
      exportRunId: '55555555-5555-4555-8555-555555555555', projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'failed' })
    expect(store.put).not.toHaveBeenCalled()
    expect(repository.fail).toHaveBeenCalledWith(expect.any(Object), expect.any(String), 'invalid_document')
  })

  it('fails invalid, oversized and unavailable export artifacts with safe codes', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: '55555555-5555-4555-8555-555555555555',
        projectId: job.projectId,
        workspaceId: job.workspaceId,
        createdBy: job.userId,
        document: { invalid: '<script>secret</script>' },
      }),
      claim: vi.fn().mockResolvedValue({ status: 'running' }),
      complete: vi.fn(),
      fail: vi.fn().mockResolvedValue({ status: 'failed' }),
    }
    const jobData = {
      exportRunId: '55555555-5555-4555-8555-555555555555',
      projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    }
    const processor = createExportProcessor({ repository, store: { put: vi.fn(), get: vi.fn() } })
    await expect(processor({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(expect.any(Object), expect.any(String), 'invalid_document')

    repository.getWorkerInput.mockResolvedValue({
      id: jobData.exportRunId, projectId: job.projectId, workspaceId: job.workspaceId,
      createdBy: job.userId, document: createValidDesignFixture(),
    })
    repository.fail.mockClear()
    await expect(createExportProcessor({
      repository,
      store: { put: vi.fn(), get: vi.fn() },
      maxArtifactBytes: 1,
    })({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(expect.any(Object), jobData.exportRunId, 'artifact_too_large')

    repository.fail.mockClear()
    await expect(createExportProcessor({
      repository,
      store: { put: vi.fn().mockRejectedValue(new Error('storage-secret')), get: vi.fn() },
    })({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(expect.any(Object), jobData.exportRunId, 'storage_unavailable')

    await expect(processor({ data: { ...jobData, unexpected: true } as never })).rejects.toThrow('invalid_export_job')
    repository.getWorkerInput.mockResolvedValue(null)
    await expect(processor({ data: jobData })).rejects.toThrow('export_run_not_found')
    repository.getWorkerInput.mockResolvedValue({
      id: jobData.exportRunId, projectId: job.projectId, workspaceId: job.workspaceId,
      createdBy: job.userId, document: createValidDesignFixture(),
    })
    repository.claim.mockResolvedValue(null)
    await expect(processor({ data: jobData })).rejects.toThrow('export_run_not_claimed')
  })

  it('deploys one immutable revision artifact through the provider adapter', async () => {
    const deploymentId = '77777777-7777-4777-8777-777777777777'
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: deploymentId,
        projectId: job.projectId,
        workspaceId: job.workspaceId,
        revisionId: '88888888-8888-4888-8888-888888888888',
        createdBy: job.userId,
        target: 'preview',
        document: (() => {
          const document = migrateDesignDocumentV1ToV2(createValidDesignFixture())
          document.nodes['about-root'] = { id: 'about-root', type: 'page', parentId: null, children: [], props: {}, style: {}, responsive: {} }
          document.pages.push({ id: 'about', name: 'About', slug: '/about', rootNodeId: 'about-root' })
          return document
        })(),
        connection: {
          id: '99999999-9999-4999-8999-999999999999',
          workspaceId: job.workspaceId,
          configurationId: 'icfg_test',
          teamId: 'team_test',
          encryptedCredential: { ciphertext: 'encrypted', iv: 'iv', authTag: 'tag', keyVersion: 1 },
        },
      }),
      claimUploading: vi.fn().mockResolvedValue({ id: deploymentId, status: 'uploading' }),
      recordArtifact: vi.fn().mockResolvedValue({
        id: deploymentId,
        projectId: job.projectId,
        workspaceId: job.workspaceId,
        revisionId: '88888888-8888-4888-8888-888888888888',
        provider: 'vercel',
        target: 'preview',
        status: 'building',
        url: null,
        errorCode: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      }),
      completeReady: vi.fn().mockResolvedValue({ id: deploymentId, status: 'ready', url: 'https://zenui-test.vercel.app' }),
      fail: vi.fn(),
    }
    const store = { put: vi.fn().mockResolvedValue(undefined), get: vi.fn() }
    const provider = {
      createDeployment: vi.fn().mockResolvedValue({ providerDeploymentId: 'dpl_test', state: 'building' }),
      getDeployment: vi.fn()
        .mockResolvedValueOnce({ state: 'building' })
        .mockResolvedValueOnce({ state: 'ready', url: 'https://zenui-test.vercel.app' }),
    }
    const processor = createDeploymentProcessor({
      repository,
      store,
      provider,
      decryptCredential: vi.fn().mockReturnValue('provider-secret-token'),
      projectNameSecret: 'project-name-secret',
      pollIntervalMs: 1,
      maxPollAttempts: 3,
    })

    await expect(processor({ data: {
      deploymentId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'ready' })
    expect(store.put).toHaveBeenCalledWith(expect.objectContaining({
      key: `deployments/${job.workspaceId}/${job.projectId}/${deploymentId}/site.bundle`,
      contentType: DEPLOYMENT_CONTENT_TYPE,
    }))
    expect(provider.createDeployment).toHaveBeenCalledWith('provider-secret-token', expect.objectContaining({
      target: 'preview',
      files: [
        expect.objectContaining({ path: 'about/index.html' }),
        expect.objectContaining({ path: 'index.html', content: expect.stringContaining('Build your next product') }),
      ],
      name: expect.stringMatching(/^zenui-[a-f0-9]{16}$/),
    }))
    expect(JSON.stringify(provider.createDeployment.mock.calls)).not.toContain('encrypted')
    expect(repository.recordArtifact).toHaveBeenCalledWith(expect.any(Object), deploymentId, expect.objectContaining({
      providerDeploymentId: 'dpl_test', checksum: expect.stringMatching(/^[a-f0-9]{64}$/),
    }))
    expect(provider.getDeployment).toHaveBeenCalledWith(
      'provider-secret-token', 'dpl_test', 'team_test',
      { projectName: expect.stringMatching(/^zenui-[a-f0-9]{16}$/), target: 'preview' },
    )
  })

  it('bundles integrity-checked owned assets into portable deployment artifacts', async () => {
    const deploymentId = '77777777-7777-4777-8777-777777777777'
    const assetId = '66666666-6666-4666-8666-666666666666'
    const bytes = Uint8Array.from([0x52, 0x49, 0x46, 0x46])
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = { assetId, alt: 'Product dashboard', decorative: false }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: deploymentId, projectId: job.projectId, workspaceId: job.workspaceId,
        revisionId: '88888888-8888-4888-8888-888888888888', createdBy: job.userId,
        target: 'preview', document,
        connection: {
          id: '99999999-9999-4999-8999-999999999999', workspaceId: job.workspaceId,
          configurationId: 'icfg_test', teamId: null, encryptedCredential: {},
        },
      }),
      getPublicationAssets: vi.fn().mockResolvedValue([{
        id: assetId, objectKey: `private/${assetId}/image.webp`, contentType: 'image/webp', bytes: bytes.byteLength,
        checksum: createHash('sha256').update(bytes).digest('hex'),
      }]),
      claimUploading: vi.fn().mockResolvedValue({ id: deploymentId, status: 'uploading' }),
      recordArtifact: vi.fn().mockResolvedValue({ id: deploymentId, status: 'building' }),
      completeReady: vi.fn().mockResolvedValue({ id: deploymentId, status: 'ready', url: 'https://zenui-test.vercel.app' }),
      fail: vi.fn(),
    }
    const provider = {
      createDeployment: vi.fn().mockResolvedValue({
        providerDeploymentId: 'dpl_test', state: 'ready', url: 'https://zenui-test.vercel.app',
      }),
      getDeployment: vi.fn(),
    }
    const assetStore = { get: vi.fn().mockResolvedValue(bytes) }
    const processor = createDeploymentProcessor({
      repository, store: { put: vi.fn().mockResolvedValue(undefined), get: vi.fn() }, provider, assetStore,
      decryptCredential: vi.fn().mockReturnValue('token'), projectNameSecret: 'secret',
    })

    await expect(processor({ data: {
      deploymentId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'ready' })
    expect(repository.getPublicationAssets).toHaveBeenCalledWith(context, job.projectId, [assetId])
    expect(provider.createDeployment).toHaveBeenCalledWith('token', expect.objectContaining({
      files: [
        { path: `assets/${assetId}.webp`, content: bytes },
        expect.objectContaining({
          path: 'index.html', content: expect.stringContaining(`src="assets/${assetId}.webp"`),
        }),
      ],
    }))
    expect(JSON.stringify(provider.createDeployment.mock.calls)).not.toMatch(/localhost|127\.0\.0\.1|private\//)
  })

  it('handles direct-ready, failed, timeout and provider exceptions safely', async () => {
    const deploymentId = '77777777-7777-4777-8777-777777777777'
    const record = {
      id: deploymentId,
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      revisionId: '88888888-8888-4888-8888-888888888888',
      provider: 'vercel' as const,
      target: 'preview' as const,
      status: 'building' as const,
      url: null,
      errorCode: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }
    const input = {
      ...record,
      createdBy: job.userId,
      document: createValidDesignFixture(),
      connection: {
        id: '99999999-9999-4999-8999-999999999999', workspaceId: job.workspaceId,
        configurationId: 'icfg_test', teamId: null, encryptedCredential: { ciphertext: 'encrypted', iv: 'iv', authTag: 'tag', keyVersion: 1 },
      },
    }
    const makeRepository = () => ({
      getWorkerInput: vi.fn().mockResolvedValue(input),
      claimUploading: vi.fn().mockResolvedValue({ ...record, status: 'uploading' }),
      recordArtifact: vi.fn().mockResolvedValue(record),
      completeReady: vi.fn().mockResolvedValue({ ...record, status: 'ready', url: 'https://zenui-test.vercel.app' }),
      fail: vi.fn().mockResolvedValue({ ...record, status: 'failed' }),
    })
    const jobData = { deploymentId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId }
    const store = { put: vi.fn().mockResolvedValue(undefined), get: vi.fn() }

    const directRepository = makeRepository()
    const direct = createDeploymentProcessor({
      repository: directRepository, store,
      provider: { createDeployment: vi.fn().mockResolvedValue({ providerDeploymentId: 'dpl_ready', state: 'ready', url: 'https://zenui-test.vercel.app' }), getDeployment: vi.fn() },
      decryptCredential: vi.fn().mockReturnValue('token'), projectNameSecret: 'secret',
    })
    await expect(direct({ data: jobData })).resolves.toMatchObject({ status: 'ready' })
    expect(directRepository.completeReady).toHaveBeenCalled()

    const failedRepository = makeRepository()
    const failed = createDeploymentProcessor({
      repository: failedRepository, store,
      provider: { createDeployment: vi.fn().mockResolvedValue({ providerDeploymentId: 'dpl_failed', state: 'building' }), getDeployment: vi.fn().mockResolvedValue({ state: 'failed' }) },
      decryptCredential: vi.fn().mockReturnValue('token'), projectNameSecret: 'secret', maxPollAttempts: 1,
    })
    await expect(failed({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(failedRepository.fail).toHaveBeenCalledWith(expect.any(Object), deploymentId, 'provider_error')

    const timeoutRepository = makeRepository()
    const timeout = createDeploymentProcessor({
      repository: timeoutRepository, store,
      provider: { createDeployment: vi.fn().mockResolvedValue({ providerDeploymentId: 'dpl_timeout', state: 'building' }), getDeployment: vi.fn().mockResolvedValue({ state: 'building' }) },
      decryptCredential: vi.fn().mockReturnValue('token'), projectNameSecret: 'secret', maxPollAttempts: 1, pollIntervalMs: 0,
    })
    await expect(timeout({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(timeoutRepository.fail).toHaveBeenCalledWith(expect.any(Object), deploymentId, 'provider_timeout')

    const exceptionRepository = makeRepository()
    const exception = createDeploymentProcessor({
      repository: exceptionRepository, store,
      provider: { createDeployment: vi.fn().mockRejectedValue(new Error('provider-secret')), getDeployment: vi.fn() },
      decryptCredential: vi.fn().mockReturnValue('token'), projectNameSecret: 'secret',
    })
    await expect(exception({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(exceptionRepository.fail).toHaveBeenCalledWith(expect.any(Object), deploymentId, 'provider_error')
  })

  it('rejects invalid, missing and already-claimed deployment jobs', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(null), claimUploading: vi.fn(), recordArtifact: vi.fn(), completeReady: vi.fn(), fail: vi.fn(),
    }
    const processor = createDeploymentProcessor({
      repository,
      store: { put: vi.fn(), get: vi.fn() }, provider: { createDeployment: vi.fn(), getDeployment: vi.fn() },
      decryptCredential: vi.fn(), projectNameSecret: 'secret',
    })
    await expect(processor({ data: {
      deploymentId: 'invalid', projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    } })).rejects.toThrow('invalid_deployment_job')
    await expect(processor({ data: {
      deploymentId: '77777777-7777-4777-8777-777777777777', projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    } })).rejects.toThrow('deployment_not_found')
    repository.getWorkerInput.mockResolvedValue({ id: '77777777-7777-4777-8777-777777777777', projectId: job.projectId, document: createValidDesignFixture() })
    repository.claimUploading.mockResolvedValue(null)
    await expect(processor({ data: {
      deploymentId: '77777777-7777-4777-8777-777777777777', projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    } })).rejects.toThrow('deployment_not_claimed')
  })

  it('fails deployment provider and artifact errors with allowlisted codes', async () => {
    const deploymentId = '77777777-7777-4777-8777-777777777777'
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: deploymentId, projectId: job.projectId, workspaceId: job.workspaceId,
        revisionId: '88888888-8888-4888-8888-888888888888', createdBy: job.userId,
        target: 'production', document: { invalid: '<script>secret</script>' },
        connection: { id: '99999999-9999-4999-8999-999999999999', workspaceId: job.workspaceId, configurationId: 'icfg', teamId: null, encryptedCredential: {} },
      }),
      claimUploading: vi.fn().mockResolvedValue({ id: deploymentId, status: 'uploading' }),
      recordArtifact: vi.fn(), completeReady: vi.fn(),
      fail: vi.fn().mockResolvedValue({ id: deploymentId, status: 'failed' }),
    }
    const processor = createDeploymentProcessor({
      repository,
      store: { put: vi.fn(), get: vi.fn() },
      provider: { createDeployment: vi.fn(), getDeployment: vi.fn() },
      decryptCredential: vi.fn().mockReturnValue('token'),
      projectNameSecret: 'secret',
    })
    await expect(processor({ data: {
      deploymentId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(expect.any(Object), deploymentId, 'invalid_artifact')
  })

  it('maps deployment storage and credential failures safely', async () => {
    const deploymentId = '77777777-7777-4777-8777-777777777777'
    const input = {
      id: deploymentId, projectId: job.projectId, workspaceId: job.workspaceId,
      revisionId: '88888888-8888-4888-8888-888888888888', createdBy: job.userId,
      target: 'preview', document: createValidDesignFixture(),
      connection: { id: '99999999-9999-4999-8999-999999999999', workspaceId: job.workspaceId, configurationId: 'icfg', teamId: null, encryptedCredential: {} },
    }
    const makeRepository = () => ({
      getWorkerInput: vi.fn().mockResolvedValue(input),
      claimUploading: vi.fn().mockResolvedValue({ id: deploymentId, status: 'uploading' }),
      recordArtifact: vi.fn(), completeReady: vi.fn(),
      fail: vi.fn().mockResolvedValue({ id: deploymentId, status: 'failed' }),
    })
    const jobData = { deploymentId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId }

    const storageRepository = makeRepository()
    const storage = createDeploymentProcessor({
      repository: storageRepository,
      store: { put: vi.fn().mockRejectedValue(new Error('storage-secret')), get: vi.fn() },
      provider: { createDeployment: vi.fn(), getDeployment: vi.fn() },
      decryptCredential: vi.fn(), projectNameSecret: 'secret',
    })
    await expect(storage({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(storageRepository.fail).toHaveBeenCalledWith(expect.any(Object), deploymentId, 'storage_unavailable')

    const credentialRepository = makeRepository()
    const credential = createDeploymentProcessor({
      repository: credentialRepository,
      store: { put: vi.fn().mockResolvedValue(undefined), get: vi.fn() },
      provider: { createDeployment: vi.fn(), getDeployment: vi.fn() },
      decryptCredential: vi.fn().mockImplementation(() => { throw new Error('cipher-secret') }),
      projectNameSecret: 'secret',
    })
    await expect(credential({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(credentialRepository.fail).toHaveBeenCalledWith(expect.any(Object), deploymentId, 'provider_auth')
  })

  it('completes contextual media proposals without invoking the text provider', async () => {
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = {
      assetId: '55555555-5555-4555-8555-555555555555', alt: 'Current product view', decorative: false,
    }
    const proposalRun = {
      ...job,
      mode: 'edit-selection' as const,
      delivery: 'proposal' as const,
      proposalIntent: 'replace-media' as const,
      proposalStatus: 'preparing' as const,
      selectedNodeId: 'image-1',
      prompt: 'Đổi hình cho giống nội dung trang hơn',
      id: job.generationRunId,
      status: 'queued',
      document,
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(proposalRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(), complete: vi.fn(),
      completeProposal: vi.fn().mockResolvedValue({
        accepted: true, run: { id: job.generationRunId, status: 'completed', proposalStatus: 'ready' },
      }),
      fail: vi.fn(),
    }
    const provider = createMockWorkerProvider([])
    const generateOperations = vi.spyOn(provider, 'generateOperations')
    const resolveProposalMedia = vi.fn().mockResolvedValue({
      assetId: '66666666-6666-4666-8666-666666666666',
      alt: 'Updated product view matching the page content',
      decorative: false as const,
    })
    const processor = createGenerationProcessor({ provider, repository, resolveProposalMedia })

    await expect(processor({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ proposalStatus: 'ready' })
    expect(generateOperations).not.toHaveBeenCalled()
    expect(resolveProposalMedia).toHaveBeenCalledWith(expect.objectContaining({
      targetNodeId: 'image-1', prompt: proposalRun.prompt,
    }))
    expect(repository.completeProposal).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      commands: [expect.objectContaining({
        type: 'UPDATE_PROPS', nodeId: 'image-1',
        patch: expect.objectContaining({ assetId: '66666666-6666-4666-8666-666666666666' }),
      })],
      proposedDocument: expect.objectContaining({ version: 2 }),
    }))
    expect(repository.complete).not.toHaveBeenCalled()
  })

  it('orchestrates one server-owned layout recipe for the exact selected section', async () => {
    const document = createValidDesignFixture()
    const planner = { planLayoutRecipe: vi.fn().mockResolvedValue({
      output: {
        version: 'layout-recipe-selection-v1', recipeId: 'section-centered',
        density: 'comfortable', mobileStack: 'column',
      },
      usage: { inputTokens: 2, outputTokens: 3, totalTokens: 5 },
    }) }
    const resolver = createLayoutProposalV2Resolver({ planner })
    await expect(resolver({
      context, projectId: job.projectId, runId: job.generationRunId,
      targetNodeId: 'section-1', prompt: 'Trình bày section cân giữa và thoáng hơn', document,
    })).resolves.toMatchObject({
      usage: { totalTokens: 5 },
      commands: [
        { type: 'UPDATE_STYLE', nodeId: 'section-1' },
        { type: 'UPDATE_RESPONSIVE_STYLE', nodeId: 'section-1', breakpoint: 'mobile' },
      ],
      document: { version: 2 },
    })
    expect(planner.planLayoutRecipe).toHaveBeenCalledOnce()
  })

  it('orchestrates one server-owned composition for the exact selected top-level section', async () => {
    const document = createValidDesignFixture()
    const planner = { planSectionComposition: vi.fn().mockResolvedValue({
      output: {
        version: 'section-composition-spec-v1', templateId: 'section-split', density: 'comfortable',
        preservation: { copy: 'preserve', cta: 'preserve', brand: 'preserve', media: 'preserve', order: 'preserve', responsive: 'preserve' },
      },
      usage: { inputTokens: 6, outputTokens: 7, totalTokens: 13 },
    }) }
    const resolver = createSectionCompositionV2Resolver({ planner })
    await expect(resolver({
      context, projectId: job.projectId, runId: job.generationRunId,
      targetNodeId: 'section-1', prompt: 'Chuyển section thành bố cục chia đôi', document,
    })).resolves.toMatchObject({
      usage: { totalTokens: 13 },
      commands: [{ type: 'REPLACE_SUBTREE', nodeId: 'section-1', rootNodeId: 'section-1' }],
      document: { version: 2 },
    })
    expect(planner.planSectionComposition).toHaveBeenCalledOnce()

    const compositionRun = {
      ...job, id: job.generationRunId, status: 'queued', mode: 'edit-selection' as const,
      delivery: 'proposal' as const, proposalIntent: 'composition' as const, proposalStatus: 'preparing' as const,
      selectedNodeId: 'section-1', prompt: 'Chuyển section thành bố cục chia đôi', document,
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(compositionRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(), complete: vi.fn(),
      completeProposal: vi.fn().mockResolvedValue({
        accepted: true, run: { id: job.generationRunId, status: 'completed', proposalStatus: 'ready' },
      }),
      fail: vi.fn(),
    }
    const textProvider = createMockWorkerProvider([])
    const textOperations = vi.spyOn(textProvider, 'generateOperations')
    await expect(createGenerationProcessor({
      provider: textProvider,
      repository,
      resolveCompositionProposalV2: resolver,
      assistantCompositionV2Enabled: true,
    })({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ proposalStatus: 'ready' })
    expect(textOperations).not.toHaveBeenCalled()
    expect(repository.completeProposal).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      commands: [expect.objectContaining({ type: 'REPLACE_SUBTREE', nodeId: 'section-1' })],
      usage: { inputTokens: 6, outputTokens: 7, totalTokens: 13 },
    }))
  })

  it('orchestrates one semantic style plan into exact-element commands without using the text editor path', async () => {
    const document = createValidDesignFixture()
    const planner = { planStyleEdit: vi.fn().mockResolvedValue({
      output: {
        version: 'style-edit-spec-v1', emphasis: 'strong', spacingDensity: 'comfortable',
        alignment: 'center', surface: 'none', mobileStack: 'preserve',
      },
      usage: { inputTokens: 4, outputTokens: 6, totalTokens: 10 },
    }) }
    const resolver = createStyleProposalV2Resolver({ planner })

    await expect(resolver({
      context, projectId: job.projectId, runId: job.generationRunId,
      targetNodeId: 'heading-1', prompt: 'Căn giữa và nhấn mạnh tiêu đề', document,
    })).resolves.toMatchObject({
      usage: { totalTokens: 10 },
      commands: [{
        type: 'UPDATE_STYLE', nodeId: 'heading-1',
        patch: { fontWeight: '700', textAlign: 'center', marginBottom: 16 },
      }],
      document: { version: 2 },
    })
    expect(planner.planStyleEdit).toHaveBeenCalledOnce()

    const styleRun = {
      ...job, id: job.generationRunId, status: 'queued', mode: 'edit-selection' as const,
      delivery: 'proposal' as const, proposalIntent: 'style' as const, proposalStatus: 'preparing' as const,
      selectedNodeId: 'heading-1', prompt: 'Căn giữa và nhấn mạnh tiêu đề', document,
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(styleRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(), complete: vi.fn(),
      completeProposal: vi.fn().mockResolvedValue({
        accepted: true, run: { id: job.generationRunId, status: 'completed', proposalStatus: 'ready' },
      }),
      fail: vi.fn(),
    }
    const textProvider = createMockWorkerProvider([])
    const textOperations = vi.spyOn(textProvider, 'generateOperations')
    await expect(createGenerationProcessor({
      provider: textProvider,
      repository,
      resolveStyleProposalV2: resolver,
      assistantStyleV2Enabled: true,
    })({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ proposalStatus: 'ready' })
    expect(textOperations).not.toHaveBeenCalled()
    expect(repository.completeProposal).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      commands: [expect.objectContaining({ type: 'UPDATE_STYLE', nodeId: 'heading-1' })],
      usage: { inputTokens: 4, outputTokens: 6, totalTokens: 10 },
    }))
  })

  it('uses the v2 media resolver only when explicitly enabled and preserves fail-soft semantics', async () => {
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = {
      assetId: '55555555-5555-4555-8555-555555555555', alt: 'Current view', decorative: false,
    }
    const proposalRun = {
      ...job, mode: 'edit-selection' as const, delivery: 'proposal' as const,
      proposalIntent: 'replace-media' as const, proposalStatus: 'preparing' as const,
      selectedNodeId: 'image-1', prompt: 'Thay bằng bảng quy trình năm bước, không có người',
      id: job.generationRunId, status: 'queued', document,
    }
    const makeRepository = () => ({
      getWorkerInput: vi.fn().mockResolvedValue(proposalRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(), complete: vi.fn(),
      completeProposal: vi.fn().mockResolvedValue({
        accepted: true, run: { id: job.generationRunId, status: 'completed', proposalStatus: 'ready' },
      }),
      fail: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'failed', proposalStatus: 'failed' }),
    })
    const legacy = vi.fn().mockResolvedValue({
      assetId: '66666666-6666-4666-8666-666666666666', alt: 'Legacy option', decorative: false as const,
    })
    const mediaReview = {
      version: 'media-proposal-review-v1' as const,
      visualBrief: {
        version: 'visual-brief-v1' as const, subject: 'Quy trình phát triển', message: 'Năm bước',
        representation: 'process-diagram' as const, composition: 'Năm cột có mũi tên',
        mustInclude: ['5 bước'], mustAvoid: ['người'], peoplePolicy: 'forbidden' as const,
        textPolicy: 'symbolic-only' as const, style: 'editorial diagram', palette: ['#2563eb'],
        aspectRatio: 'wide' as const, focalArea: 'center' as const,
        generationPrompt: 'Five step process diagram without people or readable text',
        searchQuery: null, alt: 'Sơ đồ quy trình phát triển năm bước',
      },
      candidates: [{
        candidateId: 'candidate-1', assetId: '77777777-7777-4777-8777-777777777777',
        source: 'generated' as const, score: 0.91, passed: true, safeReason: 'Phù hợp với brief.',
      }],
      selectedCandidateId: 'candidate-1', rootRequestId: job.generationRunId,
      previousProposalId: null, rejectedCandidateIds: [],
    }
    const mediaV2 = vi.fn().mockResolvedValue({
      assetId: '77777777-7777-4777-8777-777777777777',
      alt: 'Sơ đồ quy trình phát triển năm bước', decorative: false as const,
      usage: { inputTokens: 8, outputTokens: 12, totalTokens: 20 },
      mediaReview,
    })
    const repository = makeRepository()
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([]), repository,
      resolveProposalMedia: legacy, resolveProposalMediaV2: mediaV2, assistantMediaV2Enabled: true,
    })
    await expect(processor({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ proposalStatus: 'ready' })
    expect(mediaV2).toHaveBeenCalledWith(expect.objectContaining({
      targetNodeId: 'image-1', prompt: proposalRun.prompt,
    }))
    expect(legacy).not.toHaveBeenCalled()
    expect(repository.completeProposal).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      usage: { inputTokens: 8, outputTokens: 12, totalTokens: 20 },
      mediaReview,
      commands: [expect.objectContaining({ patch: expect.objectContaining({
        assetId: '77777777-7777-4777-8777-777777777777',
        alt: 'Sơ đồ quy trình phát triển năm bước',
      }) })],
    }))

    const failedRepository = makeRepository()
    const noMatch = createGenerationProcessor({
      provider: createMockWorkerProvider([]), repository: failedRepository,
      resolveProposalMedia: legacy,
      resolveProposalMediaV2: vi.fn().mockResolvedValue(null),
      assistantMediaV2Enabled: true,
    })
    await expect(noMatch({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'failed' })
    expect(legacy).not.toHaveBeenCalled()
    expect(failedRepository.completeProposal).not.toHaveBeenCalled()
    expect(failedRepository.fail).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      errorCode: 'provider_error',
    }))

    const legacyOnlyRepository = makeRepository()
    const v2ConfiguredButDisabled = vi.fn().mockRejectedValue(new Error('v2_must_not_be_called'))
    const legacyOnly = createGenerationProcessor({
      provider: createMockWorkerProvider([]), repository: legacyOnlyRepository,
      resolveProposalMedia: legacy, resolveProposalMediaV2: v2ConfiguredButDisabled,
      assistantMediaV2Enabled: false,
    })
    await expect(legacyOnly({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ proposalStatus: 'ready' })
    expect(v2ConfiguredButDisabled).not.toHaveBeenCalled()
    expect(legacy).toHaveBeenCalled()
  })

  it('orchestrates a bounded visual brief, two normalized candidates and one batch judge', async () => {
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = {
      assetId: '55555555-5555-4555-8555-555555555555', alt: 'Current view', decorative: false,
    }
    const brief: VisualBrief = {
      version: 'visual-brief-v1', subject: 'Product development workflow', message: 'Five stages',
      representation: 'process-diagram', composition: 'Five columns linked by arrows',
      mustInclude: ['five stages', 'arrows'], mustAvoid: ['people'], peoplePolicy: 'forbidden',
      textPolicy: 'symbolic-only', style: 'editorial diagram', palette: ['#2563eb'],
      aspectRatio: 'wide', focalArea: 'center',
      generationPrompt: 'Five stage product process diagram without people or readable text',
      searchQuery: null, alt: 'Five-stage product development process diagram',
    }
    const planner = { planVisualBrief: vi.fn().mockResolvedValue({
      output: brief, usage: { inputTokens: 10, outputTokens: 12, totalTokens: 22 },
    }) }
    const generator = { generate: vi.fn()
      .mockResolvedValueOnce({ bytes: new Uint8Array([1]), mimeType: 'image/png', provider: 'google', model: 'image' })
      .mockResolvedValueOnce({ bytes: new Uint8Array([2]), mimeType: 'image/png', provider: 'google', model: 'image' }) }
    const judge = { evaluateBatch: vi.fn().mockResolvedValue({
      output: [
        { candidateId: 'candidate-0', semanticRelevance: 0.88, representationMatch: 0.9, mustIncludeCoverage: 0.84, compositionFit: 0.82, websiteUsability: 0.86, confidence: 0.9, violations: [], safeReason: 'Relevant option.' },
        { candidateId: 'candidate-1', semanticRelevance: 0.96, representationMatch: 0.97, mustIncludeCoverage: 0.94, compositionFit: 0.93, websiteUsability: 0.91, confidence: 0.95, violations: [], safeReason: 'Best fit.' },
      ],
      usage: { inputTokens: 8, outputTokens: 9, totalTokens: 17 },
    }) }
    const imported = [
      { assetId: '66666666-6666-4666-8666-666666666666', bytes: new Uint8Array([11]), source: 'generated' as const },
      { assetId: '77777777-7777-4777-8777-777777777777', bytes: new Uint8Array([22]), source: 'generated' as const },
    ]
    const importCandidate = vi.fn()
      .mockResolvedValueOnce(imported[0])
      .mockResolvedValueOnce(imported[1])
    const resolver = createMediaProposalV2Resolver({
      planner, generator, judge, importCandidate,
      maxImagesPerRun: 2, multiCandidateEnabled: true,
    })

    await expect(resolver({
      context, projectId: job.projectId, runId: job.generationRunId,
      targetNodeId: 'image-1', prompt: 'Tạo bảng quy trình năm bước, không có người', document,
    })).resolves.toMatchObject({
      assetId: imported[1]!.assetId,
      usage: { inputTokens: 18, outputTokens: 21, totalTokens: 39 },
      mediaReview: {
        selectedCandidateId: 'candidate-1',
        candidates: [
          { candidateId: 'candidate-0', assetId: imported[0]!.assetId },
          { candidateId: 'candidate-1', assetId: imported[1]!.assetId },
        ],
      },
    })
    expect(generator.generate).toHaveBeenCalledTimes(2)
    expect(importCandidate).toHaveBeenNthCalledWith(1, expect.objectContaining({ candidateIndex: 0 }))
    expect(importCandidate).toHaveBeenNthCalledWith(2, expect.objectContaining({ candidateIndex: 1 }))
    expect(judge.evaluateBatch).toHaveBeenCalledOnce()
  })

  it('reports bounded media accounting without resource identifiers or user content', async () => {
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = {
      assetId: '55555555-5555-4555-8555-555555555555', alt: 'Current view', decorative: false,
    }
    const observe = vi.fn()
    const resolver = createMediaProposalV2Resolver({
      planner: { planVisualBrief: vi.fn().mockResolvedValue({
        output: {
          version: 'visual-brief-v1', subject: 'Product workflow', message: 'Five stages',
          representation: 'process-diagram', composition: 'Five columns', mustInclude: ['five stages'],
          mustAvoid: ['people'], peoplePolicy: 'forbidden', textPolicy: 'symbolic-only',
          style: 'editorial diagram', palette: [], aspectRatio: 'wide', focalArea: 'center',
          generationPrompt: 'Five stage process diagram without people or readable text', searchQuery: null,
          alt: 'Five-stage process diagram',
        },
        usage: { inputTokens: 4, outputTokens: 5, totalTokens: 9 },
      }) },
      generator: { generate: vi.fn().mockResolvedValue({
        bytes: new Uint8Array([1]), mimeType: 'image/png', provider: 'google', model: 'image',
      }) },
      judge: { evaluateBatch: vi.fn().mockResolvedValue({
        output: [{
          candidateId: 'candidate-0', semanticRelevance: 0.95, representationMatch: 0.95,
          mustIncludeCoverage: 0.9, compositionFit: 0.9, websiteUsability: 0.9,
          confidence: 0.95, violations: [], safeReason: 'Relevant.',
        }],
        usage: { inputTokens: 2, outputTokens: 3, totalTokens: 5 },
      }) },
      importCandidate: vi.fn().mockResolvedValue({
        assetId: '66666666-6666-4666-8666-666666666666', bytes: new Uint8Array([11]), source: 'generated',
      }),
      maxImagesPerRun: 1,
      observe,
    })

    await resolver({
      context, projectId: job.projectId, runId: job.generationRunId,
      targetNodeId: 'image-1', prompt: 'private user request', document,
    })

    expect(observe.mock.calls).toEqual([
      [{ stage: 'planner', outcome: 'completed', count: 1 }],
      [{ stage: 'image_generation', outcome: 'completed', count: 1 }],
      [{ stage: 'candidate', outcome: 'completed', count: 1, source: 'generated' }],
      [{ stage: 'judge', outcome: 'completed', count: 1 }],
      [{ stage: 'semantic_gate', outcome: 'accepted', count: 1 }],
    ])
    expect(JSON.stringify(observe.mock.calls)).not.toContain(job.generationRunId)
    expect(JSON.stringify(observe.mock.calls)).not.toContain(job.workspaceId)
    expect(JSON.stringify(observe.mock.calls)).not.toContain('private user request')
  })

  it('reports semantic media rejection and never reports a stock fallback for non-photo briefs', async () => {
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = {
      assetId: '55555555-5555-4555-8555-555555555555', alt: 'Current view', decorative: false,
    }
    const observe = vi.fn()
    const resolver = createMediaProposalV2Resolver({
      planner: { planVisualBrief: vi.fn().mockResolvedValue({
        output: {
          version: 'visual-brief-v1', subject: 'Product workflow', message: 'Five stages',
          representation: 'process-diagram', composition: 'Five columns', mustInclude: ['five stages'],
          mustAvoid: ['people'], peoplePolicy: 'forbidden', textPolicy: 'symbolic-only',
          style: 'editorial diagram', palette: [], aspectRatio: 'wide', focalArea: 'center',
          generationPrompt: 'Five stage process diagram without people or readable text', searchQuery: null,
          alt: 'Five-stage process diagram',
        },
        usage: { inputTokens: 1, outputTokens: 1, totalTokens: 2 },
      }) },
      generator: { generate: vi.fn().mockResolvedValue({
        bytes: new Uint8Array([1]), mimeType: 'image/png', provider: 'google', model: 'image',
      }) },
      judge: { evaluateBatch: vi.fn().mockResolvedValue({
        output: [{
          candidateId: 'candidate-0', semanticRelevance: 0.2, representationMatch: 0.1,
          mustIncludeCoverage: 0.1, compositionFit: 0.2, websiteUsability: 0.3,
          confidence: 0.9, violations: ['wrong_representation'], safeReason: 'Wrong representation.',
        }],
        usage: { inputTokens: 1, outputTokens: 1, totalTokens: 2 },
      }) },
      importCandidate: vi.fn().mockResolvedValue({
        assetId: '66666666-6666-4666-8666-666666666666', bytes: new Uint8Array([11]), source: 'generated',
      }),
      searchStock: vi.fn(), maxImagesPerRun: 1, observe,
    })

    await expect(resolver({
      context, projectId: job.projectId, runId: job.generationRunId,
      targetNodeId: 'image-1', prompt: 'private user request', document,
    })).resolves.toBeNull()
    expect(observe).toHaveBeenCalledWith({ stage: 'semantic_gate', outcome: 'rejected', count: 1 })
    expect(observe).not.toHaveBeenCalledWith(expect.objectContaining({ source: 'stock' }))
  })

  it('never falls back a non-photo brief to stock and fails soft when every candidate is rejected', async () => {
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = {
      assetId: '55555555-5555-4555-8555-555555555555', alt: 'Current view', decorative: false,
    }
    const brief: VisualBrief = {
      version: 'visual-brief-v1', subject: 'Product workflow', message: 'Five stages',
      representation: 'process-diagram', composition: 'Five columns', mustInclude: ['five stages'],
      mustAvoid: ['people'], peoplePolicy: 'forbidden', textPolicy: 'symbolic-only',
      style: 'editorial diagram', palette: [], aspectRatio: 'wide', focalArea: 'center',
      generationPrompt: 'Five stage process diagram without people or readable text', searchQuery: null,
      alt: 'Five-stage process diagram',
    }
    const stockSearch = vi.fn()
    const resolver = createMediaProposalV2Resolver({
      planner: { planVisualBrief: vi.fn().mockResolvedValue({ output: brief, usage: { inputTokens: 1, outputTokens: 1, totalTokens: 2 } }) },
      generator: { generate: vi.fn().mockResolvedValue({ bytes: new Uint8Array([1]), mimeType: 'image/png', provider: 'google', model: 'image' }) },
      judge: { evaluateBatch: vi.fn().mockResolvedValue({
        output: [{ candidateId: 'candidate-0', semanticRelevance: 0.2, representationMatch: 0.1, mustIncludeCoverage: 0.1, compositionFit: 0.2, websiteUsability: 0.3, confidence: 0.9, violations: ['wrong_representation'], safeReason: 'Wrong representation.' }],
        usage: { inputTokens: 1, outputTokens: 1, totalTokens: 2 },
      }) },
      importCandidate: vi.fn().mockResolvedValue({
        assetId: '66666666-6666-4666-8666-666666666666', bytes: new Uint8Array([11]), source: 'generated',
      }),
      searchStock: stockSearch, maxImagesPerRun: 1,
    })

    await expect(resolver({
      context, projectId: job.projectId, runId: job.generationRunId,
      targetNodeId: 'image-1', prompt: 'Tạo bảng quy trình năm bước, không có người', document,
    })).resolves.toBeNull()
    expect(stockSearch).not.toHaveBeenCalled()
  })

  it('fails invalid media materialization with preserved usage and a safe code', async () => {
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = {
      assetId: '55555555-5555-4555-8555-555555555555', alt: 'Current view', decorative: false,
    }
    const proposalRun = {
      ...job, mode: 'edit-selection' as const, delivery: 'proposal' as const,
      proposalIntent: 'replace-media' as const, proposalStatus: 'preparing' as const,
      selectedNodeId: 'image-1', prompt: 'Thay hình', id: job.generationRunId,
      expectedVersion: 2, status: 'queued', document,
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(proposalRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(), complete: vi.fn(), completeProposal: vi.fn(),
      fail: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'failed' }),
    }
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([]), repository,
      resolveProposalMediaV2: vi.fn().mockResolvedValue({
        assetId: '77777777-7777-4777-8777-777777777777', alt: 'New view', decorative: false,
        usage: { inputTokens: 3, outputTokens: 4, totalTokens: 7 },
        mediaReview: {
          version: 'media-proposal-review-v1',
          visualBrief: {
            version: 'visual-brief-v1', subject: 'New view', message: 'New view',
            representation: 'abstract', composition: 'Centered abstract form', mustInclude: [], mustAvoid: [],
            peoplePolicy: 'forbidden', textPolicy: 'none', style: 'abstract', palette: [],
            aspectRatio: 'wide', focalArea: 'center', generationPrompt: 'Abstract website visual without text',
            searchQuery: null, alt: 'New view',
          },
          candidates: [{
            candidateId: 'candidate-1', assetId: '77777777-7777-4777-8777-777777777777',
            source: 'generated', score: 0.9, passed: true, safeReason: 'Relevant.',
          }],
          selectedCandidateId: 'candidate-1', rootRequestId: job.generationRunId,
          previousProposalId: null, rejectedCandidateIds: [],
        },
      }),
      assistantMediaV2Enabled: true,
    })
    await expect(processor({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(context, job.generationRunId, {
      errorCode: 'stale_document_version',
      usage: { inputTokens: 3, outputTokens: 4, totalTokens: 7 },
      repairCount: 0,
    })
    expect(repository.completeProposal).not.toHaveBeenCalled()
  })

  it('passes bounded durable refinement context to semantic resolvers', async () => {
    const proposalRun = {
      ...job,
      mode: 'edit-selection' as const,
      delivery: 'proposal' as const,
      proposalIntent: 'style' as const,
      proposalStatus: 'preparing' as const,
      selectedNodeId: 'heading-1',
      id: job.generationRunId,
      status: 'queued',
      prompt: 'Make it shorter',
      originalRequest: 'Improve heading',
      feedbackCodes: ['copy_mismatch'] as const,
      lineage: null,
      document: createValidDesignFixture(),
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(proposalRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(), complete: vi.fn(),
      completeProposal: vi.fn().mockResolvedValue({
        accepted: true,
        run: { id: job.generationRunId, status: 'completed', proposalStatus: 'ready' },
      }),
      fail: vi.fn(),
    }
    const resolveStyleProposalV2 = vi.fn().mockResolvedValue({
      document: { ...proposalRun.document, version: 2 }, commands: [], summary: 'Bounded style',
      usage: { inputTokens: 1, outputTokens: 1, totalTokens: 2 },
    })
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([]), repository,
      resolveStyleProposalV2, assistantStyleV2Enabled: true,
    })

    await processor({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })

    expect(resolveStyleProposalV2).toHaveBeenCalledWith(expect.objectContaining({
      prompt: 'Make it shorter',
      refinement: {
        originalRequest: 'Improve heading',
        feedbackCodes: ['copy_mismatch'],
      },
    }))
  })

  it('completes proposal jobs without invoking the document-applying completion path', async () => {
    const proposalRun = {
      ...job,
      mode: 'edit-selection' as const,
      delivery: 'proposal' as const,
      proposalStatus: 'preparing' as const,
      selectedNodeId: 'heading-1',
      id: job.generationRunId,
      status: 'queued',
      document: createValidDesignFixture(),
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(proposalRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(),
      complete: vi.fn(),
      completeProposal: vi.fn().mockResolvedValue({
        accepted: true,
        run: { id: job.generationRunId, status: 'completed', proposalStatus: 'ready' },
      }),
      fail: vi.fn(),
    }
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: {
        summary: 'Clearer heading proposal',
        operations: [{ type: 'UPDATE_PROPS', nodeId: 'heading-1', patch: { text: 'Proposed heading' } }],
      } }]),
      repository,
    })

    await expect(processor({ data: {
      generationRunId: job.generationRunId,
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      userId: job.userId,
    } })).resolves.toMatchObject({ proposalStatus: 'ready' })
    expect(repository.completeProposal).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      commands: [expect.objectContaining({ type: 'UPDATE_PROPS', nodeId: 'heading-1' })],
      proposedDocument: expect.objectContaining({ version: 2 }),
      summary: 'Clearer heading proposal',
    }))
    expect(repository.complete).not.toHaveBeenCalled()
  })

  it('runs sampled shadow planning without changing the legacy proposal result', async () => {
    const proposalRun = {
      ...job,
      mode: 'edit-selection' as const,
      delivery: 'proposal' as const,
      proposalStatus: 'preparing' as const,
      selectedNodeId: 'heading-1',
      id: job.generationRunId,
      status: 'queued',
      document: createValidDesignFixture(),
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(proposalRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(), complete: vi.fn(),
      completeProposal: vi.fn().mockResolvedValue({
        accepted: true,
        run: { id: job.generationRunId, status: 'completed', proposalStatus: 'ready' },
      }),
      fail: vi.fn(),
    }
    const runAssistantShadow = vi.fn().mockResolvedValue(undefined)
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: {
        summary: 'Legacy proposal remains authoritative',
        operations: [{ type: 'UPDATE_PROPS', nodeId: 'heading-1', patch: { text: 'Legacy output' } }],
      } }]),
      repository,
      runAssistantShadow,
    })

    await processor({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })

    expect(runAssistantShadow).toHaveBeenCalledWith(expect.objectContaining({
      runId: job.generationRunId,
      targetNodeId: 'heading-1',
    }))
    expect(repository.completeProposal).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      summary: 'Legacy proposal remains authoritative',
      commands: [expect.objectContaining({ nodeId: 'heading-1' })],
    }))
  })

  it('fails shadow planning soft and still completes the legacy proposal', async () => {
    const proposalRun = {
      ...job,
      mode: 'edit-selection' as const,
      delivery: 'proposal' as const,
      proposalStatus: 'preparing' as const,
      selectedNodeId: 'heading-1',
      id: job.generationRunId,
      status: 'queued',
      document: createValidDesignFixture(),
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(proposalRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(), complete: vi.fn(),
      completeProposal: vi.fn().mockResolvedValue({
        accepted: true,
        run: { id: job.generationRunId, status: 'completed', proposalStatus: 'ready' },
      }),
      fail: vi.fn(),
    }
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: {
        summary: 'Legacy proposal',
        operations: [{ type: 'UPDATE_PROPS', nodeId: 'heading-1', patch: { text: 'Legacy output' } }],
      } }]),
      repository,
      runAssistantShadow: vi.fn().mockRejectedValue(new Error('shadow_provider_failed')),
    })

    await expect(processor({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ proposalStatus: 'ready' })
  })

  it('reports bounded proposal outcomes and token totals without run metadata', async () => {
    const proposalRun = {
      ...job,
      mode: 'edit-selection' as const,
      delivery: 'proposal' as const,
      proposalIntent: 'style' as const,
      proposalStatus: 'preparing' as const,
      selectedNodeId: 'heading-1',
      id: job.generationRunId,
      status: 'queued',
      document: createValidDesignFixture(),
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(proposalRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(), complete: vi.fn(),
      completeProposal: vi.fn().mockResolvedValue({
        accepted: true,
        run: { id: job.generationRunId, status: 'completed', proposalStatus: 'ready' },
      }),
      fail: vi.fn(),
    }
    const observe = vi.fn()
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([]), repository,
      assistantStyleV2Enabled: true,
      resolveStyleProposalV2: vi.fn().mockResolvedValue({
        document: { ...proposalRun.document, version: 2 }, commands: [], summary: 'Bounded style',
        usage: { inputTokens: 7, outputTokens: 5, totalTokens: 12 },
      }),
      observe,
    })

    await processor({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })

    expect(observe.mock.calls).toEqual([
      [{ lane: 'style', stage: 'proposal', outcome: 'started', count: 1 }],
      [{ lane: 'style', stage: 'text_tokens', outcome: 'completed', count: 12 }],
      [{ lane: 'style', stage: 'proposal', outcome: 'accepted', count: 1 }],
    ])
    expect(JSON.stringify(observe.mock.calls)).not.toContain(job.generationRunId)
    expect(JSON.stringify(observe.mock.calls)).not.toContain(job.workspaceId)
  })

  it('preserves proposal completion failure semantics', async () => {
    for (const [completionCode, expectedCode] of [
      ['scope_violation', 'scope_violation'],
      ['invalid_design_document', 'invalid_model_output'],
      ['stale_document_version', 'stale_document_version'],
    ] as const) {
      const proposalRun = {
        ...job, mode: 'edit-selection' as const, delivery: 'proposal' as const,
        proposalStatus: 'preparing' as const, selectedNodeId: 'heading-1',
        id: job.generationRunId, status: 'queued', document: createValidDesignFixture(),
      }
      const repository = {
        getWorkerInput: vi.fn().mockResolvedValue(proposalRun),
        claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
        markRepairing: vi.fn(), complete: vi.fn(),
        completeProposal: vi.fn().mockResolvedValue({ accepted: false, code: completionCode }),
        fail: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'failed' }),
      }
      const processor = createGenerationProcessor({
        provider: createMockWorkerProvider([{ output: {
          summary: 'Clearer heading proposal',
          operations: [{ type: 'UPDATE_PROPS', nodeId: 'heading-1', patch: { text: 'Proposed heading' } }],
        } }]),
        repository,
      })

      await processor({ data: {
        generationRunId: job.generationRunId, projectId: job.projectId,
        workspaceId: job.workspaceId, userId: job.userId,
      } })
      expect(repository.fail).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
        errorCode: expectedCode,
      }))
    }
  })

  it('runs edit jobs with the edit policy and operations provider path', async () => {
    const editRun = {
      ...job,
      mode: 'edit-page' as const,
      id: job.generationRunId,
      status: 'queued',
      document: createValidDesignFixture(),
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(editRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(),
      complete: vi.fn().mockResolvedValue({ accepted: true, run: { id: job.generationRunId, status: 'completed' } }),
      fail: vi.fn(),
    }
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: {
        summary: 'Improve heading',
        operations: [{ type: 'UPDATE_PROPS', nodeId: 'heading-1', patch: { text: 'Improved' } }],
      } }]),
      repository,
    })

    await expect(processor({ data: {
      generationRunId: job.generationRunId,
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      userId: job.userId,
    } })).resolves.toMatchObject({ status: 'completed' })
    expect(repository.complete).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      summary: 'Improve heading',
      document: expect.objectContaining({ version: 2 }),
    }))
  })

  it('enforces mode-specific aggregate token budgets', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({ ...job, id: job.generationRunId, status: 'queued', document: createValidDesignFixture() }),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(),
      complete: vi.fn(),
      fail: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'failed' }),
    }
    const provider = createMockWorkerProvider([{
      output: blueprint,
      usage: { inputTokens: 7, outputTokens: 6, totalTokens: 13 },
    }])
    const processor = createGenerationProcessor({
      provider,
      repository,
      generateMaxTotalTokens: 12,
    })

    await expect(processor({ data: {
      generationRunId: job.generationRunId,
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      userId: job.userId,
    } })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      errorCode: 'budget_exceeded',
      usage: { inputTokens: 7, outputTokens: 6, totalTokens: 13 },
      repairCount: 0,
    }))
    expect(repository.complete).not.toHaveBeenCalled()
  })

  it('claims, generates and atomically completes one job', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({ ...job, id: job.generationRunId, status: 'queued', document: createValidDesignFixture() }),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'repairing' }),
      complete: vi.fn().mockResolvedValue({ accepted: true, run: { id: job.generationRunId, status: 'completed' } }),
      fail: vi.fn(),
    }
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: blueprint }]),
      repository,
    })
    const metadataOnlyJob = {
      generationRunId: job.generationRunId,
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      userId: job.userId,
    }

    await expect(processor({ data: metadataOnlyJob })).resolves.toMatchObject({ status: 'completed' })
    expect(repository.claim).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({ promptVersion: AI_PROMPT_VERSION }))
    expect(repository.complete).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      document: expect.objectContaining({ version: 2 }),
      summary: 'AI generated landing page',
    }))
    expect(repository.fail).not.toHaveBeenCalled()
  })

  it('marks exhausted output and stale completion as safe failures', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({ ...job, id: job.generationRunId, status: 'queued', document: createValidDesignFixture() }),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'repairing' }),
      complete: vi.fn().mockResolvedValue({ accepted: false, code: 'stale_document_version' }),
      fail: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'failed' }),
    }
    const invalid = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: null }, { output: null }, { output: null }]),
      repository,
    })
    await expect(invalid({ data: { generationRunId: job.generationRunId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId } })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.markRepairing).not.toHaveBeenCalled()
    expect(repository.fail).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({ errorCode: 'invalid_model_output' }))

    repository.fail.mockClear()
    const stale = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: blueprint }]),
      repository,
    })
    await expect(stale({ data: { generationRunId: job.generationRunId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId } })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({ errorCode: 'stale_document_version' }))
  })

  it('maps missing and invalid completion outcomes without leaking repository details', async () => {
    const baseRepository = {
      getWorkerInput: vi.fn().mockResolvedValue({ ...job, id: job.generationRunId, status: 'queued', document: createValidDesignFixture() }),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(),
      complete: vi.fn().mockResolvedValue({ accepted: false, code: 'invalid_design_document' }),
      fail: vi.fn().mockResolvedValue(null),
    }
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: blueprint }]),
      repository: baseRepository,
      timeoutMs: 100,
      generateMaxRepairAttempts: 0,
      maxTransientRetries: 0,
    })
    await expect(processor({ data: { generationRunId: job.generationRunId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId } })).resolves.toMatchObject({ status: 'running' })
    expect(baseRepository.fail).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      errorCode: 'invalid_model_output',
    }))
    await expect(processor({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId, unexpected: true,
    } as never })).rejects.toThrow('invalid_generation_job')
  })

  it('does not claim missing or already-claimed runs', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(null),
      claim: vi.fn(), markRepairing: vi.fn(), complete: vi.fn(), fail: vi.fn(),
    }
    const processor = createGenerationProcessor({ provider: createMockWorkerProvider([]), repository })
    await expect(processor({ data: { generationRunId: job.generationRunId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId } })).rejects.toThrow('generation_run_not_found')

    repository.getWorkerInput.mockResolvedValue({ ...job, id: job.generationRunId, document: createValidDesignFixture() })
    repository.claim.mockResolvedValue(null)
    await expect(processor({ data: { generationRunId: job.generationRunId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId } })).rejects.toThrow('generation_run_not_claimed')
  })
})
