import { AI_PROMPT_VERSION } from '@zenui/ai-core'
import { DEPLOYMENT_CONTENT_TYPE } from '@zenui/deployment-core'
import { createRemoteImagePolicy, createValidDesignFixture, migrateDesignDocumentV1ToV2 } from '@zenui/design-schema'
import { describe, expect, it, vi } from 'vitest'

import {
  createDeploymentProcessor,
  createExportProcessor,
  createDesignDirectionProcessor,
  createGenerationProcessor,
  createGeminiImageGenerator,
  createGeminiProvider,
  createHybridMediaResolver,
  createMockWorkerProvider,
  workerBoundary,
} from '../src/index.js'

const job = {
  generationRunId: '11111111-1111-4111-8111-111111111111',
  projectId: '22222222-2222-4222-8222-222222222222',
  workspaceId: '33333333-3333-4333-8333-333333333333',
  userId: '44444444-4444-4444-8444-444444444444',
  mode: 'generate' as const,
  prompt: 'Create a launch landing page',
  expectedVersion: 1,
}

const context = { userId: job.userId, workspaceId: job.workspaceId }

const blueprint = {
  version: 1 as const,
  brand: 'ZenUI',
  theme: {
    primary: '#2563eb', background: '#ffffff', text: '#0f172a',
    headingFont: 'Manrope' as const, bodyFont: 'Manrope' as const,
  },
  hero: {
    heading: 'Generated by worker', paragraph: 'A safe structured page.',
    cta: { text: 'Get started', href: '#start' },
  },
  features: [
    { icon: 'star' as const, heading: 'Fast', paragraph: 'Generate focused content.' },
    { icon: 'check' as const, heading: 'Safe', paragraph: 'Keep structure server-owned.' },
  ],
}

describe('AI worker boundary', () => {
  it('never executes user code', () => {
    expect(workerBoundary).toEqual({
      responsibilities: ['ai-generation', 'asset-processing', 'export', 'deployment'],
      executesUserCode: false,
    })
  })

  it('maps Gemini structured output and usage without exposing the SDK response', async () => {
    const generateContent = vi.fn().mockResolvedValue({
      text: JSON.stringify(blueprint),
      usageMetadata: { promptTokenCount: 10, candidatesTokenCount: 20, totalTokenCount: 30 },
    })
    const provider = createGeminiProvider({
      model: 'gemini-test',
      generateContent,
    })

    const result = await provider.generateLandingPageBlueprint({
      promptVersion: AI_PROMPT_VERSION,
      prompt: 'Build safely',
      context: { mode: 'generate', request: 'Build safely', registry: [], theme: createValidDesignFixture().theme },
      signal: new AbortController().signal,
    })

    expect(result).toEqual({
      output: blueprint,
      usage: { inputTokens: 10, outputTokens: 20, totalTokens: 30 },
    })
    expect(generateContent).toHaveBeenCalledWith(expect.objectContaining({
      model: 'gemini-test',
      config: expect.objectContaining({
        responseMimeType: 'application/json',
        responseJsonSchema: expect.objectContaining({
          properties: expect.objectContaining({
            version: expect.any(Object), pagePreset: expect.any(Object), themePreset: expect.any(Object),
            navbarVariant: expect.any(Object), heroVariant: expect.any(Object), sectionOrder: expect.any(Object),
            heroHeading: expect.any(Object), features: expect.any(Object),
          }),
        }),
      }),
    }), expect.any(AbortSignal))
    expect(generateContent.mock.calls[0]?.[0].config).not.toHaveProperty('abortSignal')
    expect(generateContent.mock.calls[0]?.[0].config).not.toHaveProperty('httpOptions')
    const contents = JSON.parse(generateContent.mock.calls[0]?.[0].contents) as {
      outputContract: string
      compositionGuidance: string
    }
    expect(contents.outputContract).toContain('landing-page blueprint')
    expect(contents.compositionGuidance).toContain('Blueprint version 2')
    expect(contents.compositionGuidance).toContain('footer must be last')
    const projectedSchema = JSON.stringify(generateContent.mock.calls[0]?.[0].config.responseJsonSchema)
    expect(projectedSchema).not.toMatch(/projectId|parentId|children|nodes|pages/)
    expect(projectedSchema).not.toContain('"oneOf"')
    expect(projectedSchema).not.toContain('"anyOf"')
    expect(projectedSchema).toContain('"sectionOrder"')
    expect(projectedSchema).toContain('"logos"')
    expect(projectedSchema).toContain('"footerTagline"')
    expect(JSON.stringify(generateContent.mock.calls[0]?.[0])).not.toContain('additionalProperties')
    expect(JSON.stringify(generateContent.mock.calls[0]?.[0]).length).toBeLessThan(50_000)
  })

  it('generates one transient direction set with exactly one Gemini request and no document apply', async () => {
    const brief = {
      description: 'NovaFlow helps small product teams plan launches.',
      offer: 'A guided launch planning workspace',
      audience: 'Small product teams preparing their first launch',
      primaryGoal: 'Collect qualified consultation requests',
      cta: 'Book a consultation',
      tone: 'Clear, confident, and modern',
      brandDetails: '',
      mustHaveSections: ['introduction', 'benefits', 'trust', 'faq', 'contact'],
    } as const
    const contentBlueprint = {
      version: 1 as const,
      language: 'en' as const,
      pagePreset: 'saas' as const,
      brand: 'NovaFlow',
      announcement: 'Plan product launches with clarity',
      navLabels: ['Benefits', 'Results', 'Questions'],
      heroBadge: 'For small product teams',
      heroHeading: 'Plan every product launch with clarity',
      heroParagraph: 'Keep goals, decisions, and milestones in one shared plan.',
      heroSecondaryCta: 'See how it works',
      heroProof: 'One shared path from idea to launch day',
      heroImage: {
        query: 'product team planning launch workspace',
        alt: 'Product team planning a launch together',
      },
      contentImages: [
        { slot: 'feature-1' as const, query: 'product launch roadmap board', alt: 'Product launch roadmap board' },
        { slot: 'feature-2' as const, query: 'team reviewing launch milestones', alt: 'Team reviewing launch milestones' },
        { slot: 'feature-3' as const, query: 'collaborative launch handoff', alt: 'Collaborative product launch handoff' },
      ],
      logos: ['Acme', 'Orbit', 'Luma'],
      statsHeading: 'Momentum your team can see',
      stats: [{ value: '1', label: 'shared plan' }, { value: '24/7', label: 'available context' }, { value: '5', label: 'clear steps' }],
      featuresHeading: 'Replace scattered work with shared momentum',
      featuresParagraph: 'NovaFlow keeps every important decision in one clear story.',
      features: [
        { icon: 'check' as const, heading: 'One launch story', paragraph: 'Keep goals and milestones in one understandable plan.' },
        { icon: 'star' as const, heading: 'Clear next steps', paragraph: 'Know what needs attention next.' },
        { icon: 'arrow-right' as const, heading: 'Confident handoffs', paragraph: 'Give every teammate enough context.' },
      ],
      testimonialsHeading: 'A plan the whole team can follow',
      testimonials: [
        { quote: 'Our whole team finally sees one shared plan.', name: 'Linh Nguyen', role: 'Product lead' },
        { quote: 'We spend less time asking for status.', name: 'Minh Tran', role: 'Founder' },
      ],
      pricingHeading: 'Choose the right way to start',
      pricingParagraph: 'Start small and grow when the team is ready.',
      plans: [
        { name: 'Starter', price: 'Free', description: 'For a first launch.', features: ['One plan', 'Core guidance'], highlighted: false },
        { name: 'Growth', price: '$19/month', description: 'For growing teams.', features: ['Unlimited plans', 'Priority support'], highlighted: true },
      ],
      faqHeading: 'What to know before you begin',
      faqs: [
        { question: 'Can we start with one launch?', answer: 'Yes. Start with one active launch.' },
        { question: 'Does the team need training?', answer: 'No. Every step is clearly guided.' },
        { question: 'Can we keep our process?', answer: 'Yes. Keep what works and simplify the rest.' },
      ],
      finalCtaHeading: 'Give your next launch a clear path',
      finalCtaParagraph: 'Start with a plan the entire team can trust.',
      footerTagline: 'Guided launch planning for focused teams.',
      copyright: '© 2026 NovaFlow.',
      sectionOrder: ['logo-cloud', 'stats', 'features', 'testimonials', 'faq', 'final-cta', 'footer'],
    }
    const generateContent = vi.fn().mockResolvedValue({
      text: JSON.stringify(contentBlueprint),
      usageMetadata: { promptTokenCount: 20, candidatesTokenCount: 30, totalTokenCount: 50 },
    })
    const provider = createGeminiProvider({ model: 'gemini-test', generateContent })
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: job.generationRunId,
        projectId: job.projectId,
        workspaceId: job.workspaceId,
        createdBy: job.userId,
        expectedVersion: 1,
        round: 0,
        brief,
        document: createValidDesignFixture(),
      }),
      claim: vi.fn().mockResolvedValue({ status: 'running' }),
      complete: vi.fn().mockResolvedValue({ accepted: true, run: { status: 'completed' } }),
      fail: vi.fn(),
    }
    const resolveMedia = vi.fn().mockImplementation(({ intent }: { intent: { slot: string; alt: string } }) => Promise.resolve({
      assetId: ({
        hero: '55555555-5555-4555-8555-555555555555',
        'feature-1': '66666666-6666-4666-8666-666666666666',
        'feature-2': '77777777-7777-4777-8777-777777777777',
        'feature-3': '88888888-8888-4888-8888-888888888888',
      } as Record<string, string>)[intent.slot],
      alt: intent.alt,
      decorative: false as const,
    }))
    const processor = createDesignDirectionProcessor({ provider, repository, resolveMedia })

    await expect(processor({ data: {
      designDirectionRunId: job.generationRunId,
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      userId: job.userId,
    } })).resolves.toMatchObject({ status: 'completed' })
    expect(generateContent).toHaveBeenCalledOnce()
    expect(resolveMedia).toHaveBeenCalledTimes(4)
    expect(resolveMedia.mock.calls.map(call => (call[0] as { intent: { slot: string } }).intent.slot)).toEqual([
      'hero', 'feature-1', 'feature-2', 'feature-3',
    ])
    expect(resolveMedia).toHaveBeenCalledWith(expect.objectContaining({
      context,
      projectId: job.projectId,
      runId: job.generationRunId,
      intent: { slot: 'hero', ...contentBlueprint.heroImage },
    }))
    expect(repository.complete).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      blueprint: contentBlueprint,
      directions: expect.arrayContaining([expect.objectContaining({
        document: expect.objectContaining({
          nodes: expect.objectContaining({
            'hero-image': expect.objectContaining({
              props: {
                assetId: '55555555-5555-4555-8555-555555555555',
                alt: 'Product team planning a launch together',
                decorative: false,
              },
            }),
          }),
        }),
      })]),
      usage: { inputTokens: 20, outputTokens: 30, totalTokens: 50 },
    }))
    const providerRequest = JSON.parse(generateContent.mock.calls[0]?.[0].contents) as { outputContract: string }
    expect(providerRequest.outputContract).toContain('image search intent')
    expect(JSON.stringify(generateContent.mock.calls[0]?.[0])).not.toMatch(/providerResultId|assetId/i)
  })

  it('generates bounded image bytes through Gemini generateContent and falls back to Pexels on safe failure', async () => {
    const generateContent = vi.fn().mockResolvedValue({
      candidates: [{ content: { parts: [{ inlineData: {
        data: Buffer.from('generated-image').toString('base64'), mimeType: 'image/png',
      } }] } }],
    })
    const generator = createGeminiImageGenerator({ model: 'gemini-image-test', generateContent })
    await expect(generator.generate({
      prompt: 'Editorial product team planning launch milestones, no text or logos',
      aspectRatio: '16:9',
      signal: new AbortController().signal,
    })).resolves.toEqual({
      bytes: new Uint8Array(Buffer.from('generated-image')),
      mimeType: 'image/png',
      provider: 'google',
      model: 'gemini-image-test',
    })
    expect(generateContent).toHaveBeenCalledWith({
      model: 'gemini-image-test',
      contents: 'Editorial product team planning launch milestones, no text or logos',
      config: {
        responseModalities: ['IMAGE'],
        imageConfig: { aspectRatio: '16:9', imageSize: '1K' },
      },
    }, expect.any(AbortSignal))
    expect(JSON.stringify(generateContent.mock.calls[0]?.[0])).not.toMatch(/numberOfImages|addWatermark|enhancePrompt/)

    const generated = vi.fn().mockRejectedValue(Object.assign(new Error('safety detail'), { code: 'image_safety' }))
    const pexels = vi.fn().mockResolvedValue({ assetId: '55555555-5555-4555-8555-555555555555', alt: 'Fallback', decorative: false })
    const resolver = createHybridMediaResolver({ generateOwned: generated, resolvePexels: pexels })
    await expect(resolver({ slot: 'hero', query: 'product team planning', alt: 'Fallback' })).resolves.toMatchObject({
      assetId: '55555555-5555-4555-8555-555555555555',
    })
    expect(generated).toHaveBeenCalledOnce()
    expect(pexels).toHaveBeenCalledOnce()

    generated.mockResolvedValueOnce({ assetId: '66666666-6666-4666-8666-666666666666', alt: 'Generated', decorative: false })
    await expect(resolver({ slot: 'feature-1', query: 'launch roadmap', alt: 'Generated' })).resolves.toMatchObject({
      assetId: '66666666-6666-4666-8666-666666666666',
    })
    expect(pexels).toHaveBeenCalledOnce()
  })

  it('rejects Gemini image responses without exactly one supported inline image', async () => {
    for (const response of [
      { candidates: [] },
      { candidates: [{ content: { parts: [{ text: 'No image available' }] } }] },
      { candidates: [{ content: { parts: [{ inlineData: { data: 'aW1hZ2U=', mimeType: 'image/gif' } }] } }] },
      { candidates: [{ content: { parts: [
        { inlineData: { data: 'aW1hZ2U=', mimeType: 'image/png' } },
        { inlineData: { data: 'aW1hZ2U=', mimeType: 'image/png' } },
      ] } }] },
    ]) {
      const generator = createGeminiImageGenerator({
        model: 'gemini-image-test',
        generateContent: vi.fn().mockResolvedValue(response),
      })
      await expect(generator.generate({
        prompt: 'A bounded website image', aspectRatio: '4:3', signal: new AbortController().signal,
      })).rejects.toMatchObject({ code: 'image_invalid' })
    }
  })

  it('normalizes malformed JSON and provider errors to safe codes', async () => {
    const malformed = createGeminiProvider({
      model: 'gemini-test',
      generateContent: vi.fn().mockResolvedValue({ text: '{bad json' }),
    })
    await expect(malformed.generateLandingPageBlueprint({
      promptVersion: AI_PROMPT_VERSION, prompt: 'Build',
      context: { mode: 'generate', request: 'Build', registry: [], theme: createValidDesignFixture().theme },
      signal: new AbortController().signal,
    })).rejects.toMatchObject({ code: 'provider_error' })

    const denied = createGeminiProvider({
      model: 'gemini-test',
      generateContent: vi.fn().mockRejectedValue(Object.assign(new Error('API key leaked-provider-detail'), { status: 401 })),
    })
    await expect(denied.generateLandingPageBlueprint({
      promptVersion: AI_PROMPT_VERSION, prompt: 'Build',
      context: { mode: 'generate', request: 'Build', registry: [], theme: createValidDesignFixture().theme },
      signal: new AbortController().signal,
    })).rejects.toMatchObject({ code: 'provider_auth', message: 'provider_auth' })

    for (const [error, code] of [
      [Object.assign(new Error('limited'), { status: 429 }), 'provider_rate_limit'],
      [Object.assign(new Error('unavailable'), { status: 503 }), 'provider_transient'],
      [Object.assign(new Error('aborted'), { name: 'AbortError' }), 'provider_timeout'],
    ] as const) {
      const failed = createGeminiProvider({
        model: 'gemini-test',
        generateContent: vi.fn().mockRejectedValue(error),
      })
      await expect(failed.generateLandingPageBlueprint({
        promptVersion: AI_PROMPT_VERSION, prompt: 'Build',
        context: { mode: 'generate', request: 'Build', registry: [], theme: createValidDesignFixture().theme },
        signal: new AbortController().signal,
      })).rejects.toMatchObject({ code, message: code })
    }
  })

  it('maps Gemini bad requests to a distinct safe failure code', async () => {
    const failed = createGeminiProvider({
      model: 'gemini-test',
      generateContent: vi.fn().mockRejectedValue(Object.assign(new Error('provider detail'), { status: 400 })),
    })
    await expect(failed.generateOperations({
      promptVersion: AI_PROMPT_VERSION, prompt: 'Shorten heading',
      context: { mode: 'edit-selection', request: 'Shorten heading', registry: [], theme: createValidDesignFixture().theme },
      signal: new AbortController().signal,
    })).rejects.toMatchObject({ code: 'provider_bad_request', message: 'provider_bad_request' })
  })

  it('projects selection edits to a Gemini-compatible copy schema', async () => {
    const generateContent = vi.fn().mockResolvedValue({
      text: JSON.stringify({ summary: 'Shortened Hero heading', updates: [{
        nodeId: 'hero-heading', property: 'text', value: 'AI chăm sóc khách hàng hiệu quả hơn',
      }] }),
      usageMetadata: { promptTokenCount: 4, candidatesTokenCount: 6, totalTokenCount: 10 },
    })
    const provider = createGeminiProvider({ model: 'gemini-test', generateContent })
    const document = createValidDesignFixture()
    document.nodes['hero-1'] = {
      id: 'hero-1', type: 'hero', parentId: 'page-root', children: ['hero-heading'],
      props: { label: 'Hero' }, style: {}, responsive: {},
    }
    document.nodes['hero-heading'] = {
      id: 'hero-heading', type: 'heading', parentId: 'hero-1', children: [],
      props: { text: 'Tự động hóa quy trình chăm sóc khách hàng với sức mạnh AI', level: 1 }, style: {}, responsive: {},
    }

    const result = await provider.generateOperations({
      promptVersion: AI_PROMPT_VERSION,
      prompt: 'Đổi tiêu đề Hero ngắn gọn hơn',
      context: {
        mode: 'edit-selection', request: 'Đổi tiêu đề Hero ngắn gọn hơn', registry: [], theme: document.theme,
        selectedNodeId: 'hero-1', selectedNodes: {
          'hero-1': document.nodes['hero-1'], 'hero-heading': document.nodes['hero-heading'],
        }, editableProps: { 'hero-heading': ['text', 'level'] },
        editIntent: 'copy',
      },
      signal: new AbortController().signal,
    })

    expect(result.output).toEqual({
      summary: 'Shortened Hero heading',
      operations: [{
        type: 'UPDATE_PROPS', nodeId: 'hero-heading', patch: { text: 'AI chăm sóc khách hàng hiệu quả hơn' },
      }],
    })
    const schema = JSON.stringify(generateContent.mock.calls[0]?.[0].config.responseJsonSchema)
    expect(schema.length).toBeLessThan(8_000)
    expect(schema).not.toContain('oneOf')
    expect(schema).not.toContain('anyOf')
    expect(schema).not.toContain('INSERT_NODE')
    expect(schema).not.toContain('UPDATE_PROPS')
    expect(schema).not.toContain('hero-heading')
    expect(schema).toContain('updates')
    expect(schema).toContain('property')
    const contents = JSON.parse(generateContent.mock.calls[0]?.[0].contents) as { editGuidance?: string }
    expect(contents.editGuidance).toContain('fewest operations')
  })

  it('uses fallback usage counts and the static edit schema for edit requests', async () => {
    const generateContent = vi.fn().mockResolvedValue({
      text: JSON.stringify({
        summary: 'Edit', updates: [{ nodeId: 'heading-1', property: 'text', value: 'Edited' }],
      }),
      usageMetadata: { promptTokenCount: 4, candidatesTokenCount: 6 },
    })
    const provider = createGeminiProvider({ model: 'gemini-test', generateContent, editMaxOutputTokens: 1024 })
    const result = await provider.generateOperations({
      promptVersion: AI_PROMPT_VERSION, prompt: 'Edit',
      context: {
        mode: 'edit-page', request: 'Edit', registry: [], theme: createValidDesignFixture().theme,
        document: createValidDesignFixture(), editableProps: { 'heading-1': ['text', 'level'] }, editIntent: 'copy',
      },
      repair: { attempt: 1, issues: ['invalid output'] },
      signal: new AbortController().signal,
    })

    expect(result).toMatchObject({
      output: {
        summary: 'Edit', operations: [{ type: 'UPDATE_PROPS', nodeId: 'heading-1', patch: { text: 'Edited' } }],
      },
      usage: { inputTokens: 4, outputTokens: 6, totalTokens: 10 },
    })
    expect(generateContent).toHaveBeenCalledWith(expect.objectContaining({
      config: expect.objectContaining({ maxOutputTokens: 1024, responseMimeType: 'application/json' }),
    }), expect.any(AbortSignal))
    expect(generateContent.mock.calls[0]?.[0].config.responseJsonSchema).toMatchObject({
      properties: { summary: expect.any(Object), updates: expect.any(Object) },
    })
    expect(JSON.parse(generateContent.mock.calls[0]?.[0].contents)).toMatchObject({
      outputContract: expect.stringContaining('operation batch'),
    })
  })

  it('compiles and uploads one deterministic multi-route ZIP without executing user code', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: '55555555-5555-4555-8555-555555555555',
        projectId: job.projectId,
        workspaceId: job.workspaceId,
        createdBy: job.userId,
        document: (() => {
          const document = migrateDesignDocumentV1ToV2(createValidDesignFixture())
          document.nodes['about-root'] = { id: 'about-root', type: 'page', parentId: null, children: [], props: {}, style: {}, responsive: {} }
          document.pages.push({ id: 'about', name: 'About', slug: '/about', rootNodeId: 'about-root' })
          return document
        })(),
      }),
      claim: vi.fn().mockResolvedValue({ status: 'running' }),
      complete: vi.fn().mockResolvedValue({ status: 'completed' }),
      fail: vi.fn(),
    }
    const store = { put: vi.fn().mockResolvedValue(undefined), get: vi.fn() }
    const processor = createExportProcessor({ repository, store, maxArtifactBytes: 2 * 1024 * 1024 })
    const exportJob = {
      exportRunId: '55555555-5555-4555-8555-555555555555',
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      userId: job.userId,
    }

    await expect(processor({ data: exportJob })).resolves.toMatchObject({ status: 'completed' })
    expect(store.put).toHaveBeenCalledWith(expect.objectContaining({
      key: `exports/${job.workspaceId}/${job.projectId}/${exportJob.exportRunId}/site.zip`,
      contentType: 'application/zip',
      checksum: expect.stringMatching(/^[a-f0-9]{64}$/),
      content: expect.any(Uint8Array),
    }))
    const uploaded = store.put.mock.calls[0]?.[0] as { content: Uint8Array } | undefined
    expect(uploaded?.content.slice(0, 4)).toEqual(Uint8Array.from([0x50, 0x4b, 0x03, 0x04]))
    expect(repository.complete).toHaveBeenCalledWith(expect.any(Object), exportJob.exportRunId, expect.objectContaining({
      artifactKey: expect.stringContaining(exportJob.exportRunId),
      bytes: expect.any(Number),
      routeCount: 2,
    }))
  })

  it('compiles owned asset references into immutable export URLs and CSP', async () => {
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = {
      assetId: '66666666-6666-4666-8666-666666666666', alt: 'Product dashboard', decorative: false,
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: '55555555-5555-4555-8555-555555555555', projectId: job.projectId,
        workspaceId: job.workspaceId, createdBy: job.userId, document,
      }),
      claim: vi.fn().mockResolvedValue({ status: 'running' }),
      complete: vi.fn().mockResolvedValue({ status: 'completed' }),
      fail: vi.fn(),
    }
    const store = { put: vi.fn().mockResolvedValue(undefined), get: vi.fn() }
    const processor = createExportProcessor({ repository, store, assetOrigin: 'https://assets.example.com' })

    await expect(processor({ data: {
      exportRunId: '55555555-5555-4555-8555-555555555555', projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'completed' })
    const uploaded = store.put.mock.calls[0]?.[0] as { content: Uint8Array } | undefined
    const archive = new TextDecoder().decode(uploaded?.content)
    expect(archive).toContain('src="https://assets.example.com/a/66666666-6666-4666-8666-666666666666"')
    expect(archive).toContain('img-src https://assets.example.com')
  })

  it('rejects export images outside the shared policy before storage', async () => {
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = { src: 'https://evil.example.test/hero.png', alt: 'Denied' }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: '55555555-5555-4555-8555-555555555555', projectId: job.projectId,
        workspaceId: job.workspaceId, createdBy: job.userId, document,
      }),
      claim: vi.fn().mockResolvedValue({ status: 'running' }),
      complete: vi.fn(),
      fail: vi.fn().mockResolvedValue({ status: 'failed' }),
    }
    const store = { put: vi.fn(), get: vi.fn() }
    const processor = createExportProcessor({
      repository, store, imagePolicy: createRemoteImagePolicy('images.example.com'),
    })
    await expect(processor({ data: {
      exportRunId: '55555555-5555-4555-8555-555555555555', projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'failed' })
    expect(store.put).not.toHaveBeenCalled()
    expect(repository.fail).toHaveBeenCalledWith(expect.any(Object), expect.any(String), 'invalid_document')
  })

  it('fails invalid, oversized and unavailable export artifacts with safe codes', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: '55555555-5555-4555-8555-555555555555',
        projectId: job.projectId,
        workspaceId: job.workspaceId,
        createdBy: job.userId,
        document: { invalid: '<script>secret</script>' },
      }),
      claim: vi.fn().mockResolvedValue({ status: 'running' }),
      complete: vi.fn(),
      fail: vi.fn().mockResolvedValue({ status: 'failed' }),
    }
    const jobData = {
      exportRunId: '55555555-5555-4555-8555-555555555555',
      projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    }
    const processor = createExportProcessor({ repository, store: { put: vi.fn(), get: vi.fn() } })
    await expect(processor({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(expect.any(Object), expect.any(String), 'invalid_document')

    repository.getWorkerInput.mockResolvedValue({
      id: jobData.exportRunId, projectId: job.projectId, workspaceId: job.workspaceId,
      createdBy: job.userId, document: createValidDesignFixture(),
    })
    repository.fail.mockClear()
    await expect(createExportProcessor({
      repository,
      store: { put: vi.fn(), get: vi.fn() },
      maxArtifactBytes: 1,
    })({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(expect.any(Object), jobData.exportRunId, 'artifact_too_large')

    repository.fail.mockClear()
    await expect(createExportProcessor({
      repository,
      store: { put: vi.fn().mockRejectedValue(new Error('storage-secret')), get: vi.fn() },
    })({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(expect.any(Object), jobData.exportRunId, 'storage_unavailable')

    await expect(processor({ data: { ...jobData, unexpected: true } as never })).rejects.toThrow('invalid_export_job')
    repository.getWorkerInput.mockResolvedValue(null)
    await expect(processor({ data: jobData })).rejects.toThrow('export_run_not_found')
    repository.getWorkerInput.mockResolvedValue({
      id: jobData.exportRunId, projectId: job.projectId, workspaceId: job.workspaceId,
      createdBy: job.userId, document: createValidDesignFixture(),
    })
    repository.claim.mockResolvedValue(null)
    await expect(processor({ data: jobData })).rejects.toThrow('export_run_not_claimed')
  })

  it('deploys one immutable revision artifact through the provider adapter', async () => {
    const deploymentId = '77777777-7777-4777-8777-777777777777'
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: deploymentId,
        projectId: job.projectId,
        workspaceId: job.workspaceId,
        revisionId: '88888888-8888-4888-8888-888888888888',
        createdBy: job.userId,
        target: 'preview',
        document: (() => {
          const document = migrateDesignDocumentV1ToV2(createValidDesignFixture())
          document.nodes['about-root'] = { id: 'about-root', type: 'page', parentId: null, children: [], props: {}, style: {}, responsive: {} }
          document.pages.push({ id: 'about', name: 'About', slug: '/about', rootNodeId: 'about-root' })
          return document
        })(),
        connection: {
          id: '99999999-9999-4999-8999-999999999999',
          workspaceId: job.workspaceId,
          configurationId: 'icfg_test',
          teamId: 'team_test',
          encryptedCredential: { ciphertext: 'encrypted', iv: 'iv', authTag: 'tag', keyVersion: 1 },
        },
      }),
      claimUploading: vi.fn().mockResolvedValue({ id: deploymentId, status: 'uploading' }),
      recordArtifact: vi.fn().mockResolvedValue({
        id: deploymentId,
        projectId: job.projectId,
        workspaceId: job.workspaceId,
        revisionId: '88888888-8888-4888-8888-888888888888',
        provider: 'vercel',
        target: 'preview',
        status: 'building',
        url: null,
        errorCode: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      }),
      completeReady: vi.fn().mockResolvedValue({ id: deploymentId, status: 'ready', url: 'https://zenui-test.vercel.app' }),
      fail: vi.fn(),
    }
    const store = { put: vi.fn().mockResolvedValue(undefined), get: vi.fn() }
    const provider = {
      createDeployment: vi.fn().mockResolvedValue({ providerDeploymentId: 'dpl_test', state: 'building' }),
      getDeployment: vi.fn()
        .mockResolvedValueOnce({ state: 'building' })
        .mockResolvedValueOnce({ state: 'ready', url: 'https://zenui-test.vercel.app' }),
    }
    const processor = createDeploymentProcessor({
      repository,
      store,
      provider,
      decryptCredential: vi.fn().mockReturnValue('provider-secret-token'),
      projectNameSecret: 'project-name-secret',
      pollIntervalMs: 1,
      maxPollAttempts: 3,
    })

    await expect(processor({ data: {
      deploymentId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'ready' })
    expect(store.put).toHaveBeenCalledWith(expect.objectContaining({
      key: `deployments/${job.workspaceId}/${job.projectId}/${deploymentId}/site.bundle`,
      contentType: DEPLOYMENT_CONTENT_TYPE,
    }))
    expect(provider.createDeployment).toHaveBeenCalledWith('provider-secret-token', expect.objectContaining({
      target: 'preview',
      files: [
        expect.objectContaining({ path: 'about/index.html' }),
        expect.objectContaining({ path: 'index.html', content: expect.stringContaining('Build your next product') }),
      ],
      name: expect.stringMatching(/^zenui-[a-f0-9]{16}$/),
    }))
    expect(JSON.stringify(provider.createDeployment.mock.calls)).not.toContain('encrypted')
    expect(repository.recordArtifact).toHaveBeenCalledWith(expect.any(Object), deploymentId, expect.objectContaining({
      providerDeploymentId: 'dpl_test', checksum: expect.stringMatching(/^[a-f0-9]{64}$/),
    }))
  })

  it('compiles owned asset references into immutable deployment artifacts', async () => {
    const deploymentId = '77777777-7777-4777-8777-777777777777'
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = {
      assetId: '66666666-6666-4666-8666-666666666666', alt: 'Product dashboard', decorative: false,
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: deploymentId, projectId: job.projectId, workspaceId: job.workspaceId,
        revisionId: '88888888-8888-4888-8888-888888888888', createdBy: job.userId,
        target: 'preview', document,
        connection: {
          id: '99999999-9999-4999-8999-999999999999', workspaceId: job.workspaceId,
          configurationId: 'icfg_test', teamId: null, encryptedCredential: {},
        },
      }),
      claimUploading: vi.fn().mockResolvedValue({ id: deploymentId, status: 'uploading' }),
      recordArtifact: vi.fn().mockResolvedValue({ id: deploymentId, status: 'building' }),
      completeReady: vi.fn().mockResolvedValue({ id: deploymentId, status: 'ready', url: 'https://zenui-test.vercel.app' }),
      fail: vi.fn(),
    }
    const provider = {
      createDeployment: vi.fn().mockResolvedValue({
        providerDeploymentId: 'dpl_test', state: 'ready', url: 'https://zenui-test.vercel.app',
      }),
      getDeployment: vi.fn(),
    }
    const processor = createDeploymentProcessor({
      repository, store: { put: vi.fn().mockResolvedValue(undefined), get: vi.fn() }, provider,
      decryptCredential: vi.fn().mockReturnValue('token'), projectNameSecret: 'secret',
      assetOrigin: 'https://assets.example.com',
    })

    await expect(processor({ data: {
      deploymentId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'ready' })
    expect(provider.createDeployment).toHaveBeenCalledWith('token', expect.objectContaining({
      files: [expect.objectContaining({
        path: 'index.html',
        content: expect.stringContaining('src="https://assets.example.com/a/66666666-6666-4666-8666-666666666666"'),
      })],
    }))
  })

  it('handles direct-ready, failed, timeout and provider exceptions safely', async () => {
    const deploymentId = '77777777-7777-4777-8777-777777777777'
    const record = {
      id: deploymentId,
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      revisionId: '88888888-8888-4888-8888-888888888888',
      provider: 'vercel' as const,
      target: 'preview' as const,
      status: 'building' as const,
      url: null,
      errorCode: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }
    const input = {
      ...record,
      createdBy: job.userId,
      document: createValidDesignFixture(),
      connection: {
        id: '99999999-9999-4999-8999-999999999999', workspaceId: job.workspaceId,
        configurationId: 'icfg_test', teamId: null, encryptedCredential: { ciphertext: 'encrypted', iv: 'iv', authTag: 'tag', keyVersion: 1 },
      },
    }
    const makeRepository = () => ({
      getWorkerInput: vi.fn().mockResolvedValue(input),
      claimUploading: vi.fn().mockResolvedValue({ ...record, status: 'uploading' }),
      recordArtifact: vi.fn().mockResolvedValue(record),
      completeReady: vi.fn().mockResolvedValue({ ...record, status: 'ready', url: 'https://zenui-test.vercel.app' }),
      fail: vi.fn().mockResolvedValue({ ...record, status: 'failed' }),
    })
    const jobData = { deploymentId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId }
    const store = { put: vi.fn().mockResolvedValue(undefined), get: vi.fn() }

    const directRepository = makeRepository()
    const direct = createDeploymentProcessor({
      repository: directRepository, store,
      provider: { createDeployment: vi.fn().mockResolvedValue({ providerDeploymentId: 'dpl_ready', state: 'ready', url: 'https://zenui-test.vercel.app' }), getDeployment: vi.fn() },
      decryptCredential: vi.fn().mockReturnValue('token'), projectNameSecret: 'secret',
    })
    await expect(direct({ data: jobData })).resolves.toMatchObject({ status: 'ready' })
    expect(directRepository.completeReady).toHaveBeenCalled()

    const failedRepository = makeRepository()
    const failed = createDeploymentProcessor({
      repository: failedRepository, store,
      provider: { createDeployment: vi.fn().mockResolvedValue({ providerDeploymentId: 'dpl_failed', state: 'building' }), getDeployment: vi.fn().mockResolvedValue({ state: 'failed' }) },
      decryptCredential: vi.fn().mockReturnValue('token'), projectNameSecret: 'secret', maxPollAttempts: 1,
    })
    await expect(failed({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(failedRepository.fail).toHaveBeenCalledWith(expect.any(Object), deploymentId, 'provider_error')

    const timeoutRepository = makeRepository()
    const timeout = createDeploymentProcessor({
      repository: timeoutRepository, store,
      provider: { createDeployment: vi.fn().mockResolvedValue({ providerDeploymentId: 'dpl_timeout', state: 'building' }), getDeployment: vi.fn().mockResolvedValue({ state: 'building' }) },
      decryptCredential: vi.fn().mockReturnValue('token'), projectNameSecret: 'secret', maxPollAttempts: 1, pollIntervalMs: 0,
    })
    await expect(timeout({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(timeoutRepository.fail).toHaveBeenCalledWith(expect.any(Object), deploymentId, 'provider_timeout')

    const exceptionRepository = makeRepository()
    const exception = createDeploymentProcessor({
      repository: exceptionRepository, store,
      provider: { createDeployment: vi.fn().mockRejectedValue(new Error('provider-secret')), getDeployment: vi.fn() },
      decryptCredential: vi.fn().mockReturnValue('token'), projectNameSecret: 'secret',
    })
    await expect(exception({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(exceptionRepository.fail).toHaveBeenCalledWith(expect.any(Object), deploymentId, 'provider_error')
  })

  it('rejects invalid, missing and already-claimed deployment jobs', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(null), claimUploading: vi.fn(), recordArtifact: vi.fn(), completeReady: vi.fn(), fail: vi.fn(),
    }
    const processor = createDeploymentProcessor({
      repository,
      store: { put: vi.fn(), get: vi.fn() }, provider: { createDeployment: vi.fn(), getDeployment: vi.fn() },
      decryptCredential: vi.fn(), projectNameSecret: 'secret',
    })
    await expect(processor({ data: {
      deploymentId: 'invalid', projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    } })).rejects.toThrow('invalid_deployment_job')
    await expect(processor({ data: {
      deploymentId: '77777777-7777-4777-8777-777777777777', projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    } })).rejects.toThrow('deployment_not_found')
    repository.getWorkerInput.mockResolvedValue({ id: '77777777-7777-4777-8777-777777777777', projectId: job.projectId, document: createValidDesignFixture() })
    repository.claimUploading.mockResolvedValue(null)
    await expect(processor({ data: {
      deploymentId: '77777777-7777-4777-8777-777777777777', projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    } })).rejects.toThrow('deployment_not_claimed')
  })

  it('fails deployment provider and artifact errors with allowlisted codes', async () => {
    const deploymentId = '77777777-7777-4777-8777-777777777777'
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({
        id: deploymentId, projectId: job.projectId, workspaceId: job.workspaceId,
        revisionId: '88888888-8888-4888-8888-888888888888', createdBy: job.userId,
        target: 'production', document: { invalid: '<script>secret</script>' },
        connection: { id: '99999999-9999-4999-8999-999999999999', workspaceId: job.workspaceId, configurationId: 'icfg', teamId: null, encryptedCredential: {} },
      }),
      claimUploading: vi.fn().mockResolvedValue({ id: deploymentId, status: 'uploading' }),
      recordArtifact: vi.fn(), completeReady: vi.fn(),
      fail: vi.fn().mockResolvedValue({ id: deploymentId, status: 'failed' }),
    }
    const processor = createDeploymentProcessor({
      repository,
      store: { put: vi.fn(), get: vi.fn() },
      provider: { createDeployment: vi.fn(), getDeployment: vi.fn() },
      decryptCredential: vi.fn().mockReturnValue('token'),
      projectNameSecret: 'secret',
    })
    await expect(processor({ data: {
      deploymentId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(expect.any(Object), deploymentId, 'invalid_artifact')
  })

  it('maps deployment storage and credential failures safely', async () => {
    const deploymentId = '77777777-7777-4777-8777-777777777777'
    const input = {
      id: deploymentId, projectId: job.projectId, workspaceId: job.workspaceId,
      revisionId: '88888888-8888-4888-8888-888888888888', createdBy: job.userId,
      target: 'preview', document: createValidDesignFixture(),
      connection: { id: '99999999-9999-4999-8999-999999999999', workspaceId: job.workspaceId, configurationId: 'icfg', teamId: null, encryptedCredential: {} },
    }
    const makeRepository = () => ({
      getWorkerInput: vi.fn().mockResolvedValue(input),
      claimUploading: vi.fn().mockResolvedValue({ id: deploymentId, status: 'uploading' }),
      recordArtifact: vi.fn(), completeReady: vi.fn(),
      fail: vi.fn().mockResolvedValue({ id: deploymentId, status: 'failed' }),
    })
    const jobData = { deploymentId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId }

    const storageRepository = makeRepository()
    const storage = createDeploymentProcessor({
      repository: storageRepository,
      store: { put: vi.fn().mockRejectedValue(new Error('storage-secret')), get: vi.fn() },
      provider: { createDeployment: vi.fn(), getDeployment: vi.fn() },
      decryptCredential: vi.fn(), projectNameSecret: 'secret',
    })
    await expect(storage({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(storageRepository.fail).toHaveBeenCalledWith(expect.any(Object), deploymentId, 'storage_unavailable')

    const credentialRepository = makeRepository()
    const credential = createDeploymentProcessor({
      repository: credentialRepository,
      store: { put: vi.fn().mockResolvedValue(undefined), get: vi.fn() },
      provider: { createDeployment: vi.fn(), getDeployment: vi.fn() },
      decryptCredential: vi.fn().mockImplementation(() => { throw new Error('cipher-secret') }),
      projectNameSecret: 'secret',
    })
    await expect(credential({ data: jobData })).resolves.toMatchObject({ status: 'failed' })
    expect(credentialRepository.fail).toHaveBeenCalledWith(expect.any(Object), deploymentId, 'provider_auth')
  })

  it('completes contextual media proposals without invoking the text provider', async () => {
    const document = createValidDesignFixture()
    document.nodes['image-1']!.props = {
      assetId: '55555555-5555-4555-8555-555555555555', alt: 'Current product view', decorative: false,
    }
    const proposalRun = {
      ...job,
      mode: 'edit-selection' as const,
      delivery: 'proposal' as const,
      proposalIntent: 'replace-media' as const,
      proposalStatus: 'preparing' as const,
      selectedNodeId: 'image-1',
      prompt: 'Đổi hình cho giống nội dung trang hơn',
      id: job.generationRunId,
      status: 'queued',
      document,
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(proposalRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(), complete: vi.fn(),
      completeProposal: vi.fn().mockResolvedValue({
        accepted: true, run: { id: job.generationRunId, status: 'completed', proposalStatus: 'ready' },
      }),
      fail: vi.fn(),
    }
    const provider = createMockWorkerProvider([])
    const generateOperations = vi.spyOn(provider, 'generateOperations')
    const resolveProposalMedia = vi.fn().mockResolvedValue({
      assetId: '66666666-6666-4666-8666-666666666666',
      alt: 'Updated product view matching the page content',
      decorative: false as const,
    })
    const processor = createGenerationProcessor({ provider, repository, resolveProposalMedia })

    await expect(processor({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId,
    } })).resolves.toMatchObject({ proposalStatus: 'ready' })
    expect(generateOperations).not.toHaveBeenCalled()
    expect(resolveProposalMedia).toHaveBeenCalledWith(expect.objectContaining({
      targetNodeId: 'image-1', prompt: proposalRun.prompt,
    }))
    expect(repository.completeProposal).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      commands: [expect.objectContaining({
        type: 'UPDATE_PROPS', nodeId: 'image-1',
        patch: expect.objectContaining({ assetId: '66666666-6666-4666-8666-666666666666' }),
      })],
      proposedDocument: expect.objectContaining({ version: 2 }),
    }))
    expect(repository.complete).not.toHaveBeenCalled()
  })

  it('completes proposal jobs without invoking the document-applying completion path', async () => {
    const proposalRun = {
      ...job,
      mode: 'edit-selection' as const,
      delivery: 'proposal' as const,
      proposalStatus: 'preparing' as const,
      selectedNodeId: 'heading-1',
      id: job.generationRunId,
      status: 'queued',
      document: createValidDesignFixture(),
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(proposalRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(),
      complete: vi.fn(),
      completeProposal: vi.fn().mockResolvedValue({
        accepted: true,
        run: { id: job.generationRunId, status: 'completed', proposalStatus: 'ready' },
      }),
      fail: vi.fn(),
    }
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: {
        summary: 'Clearer heading proposal',
        operations: [{ type: 'UPDATE_PROPS', nodeId: 'heading-1', patch: { text: 'Proposed heading' } }],
      } }]),
      repository,
    })

    await expect(processor({ data: {
      generationRunId: job.generationRunId,
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      userId: job.userId,
    } })).resolves.toMatchObject({ proposalStatus: 'ready' })
    expect(repository.completeProposal).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      commands: [expect.objectContaining({ type: 'UPDATE_PROPS', nodeId: 'heading-1' })],
      proposedDocument: expect.objectContaining({ version: 2 }),
      summary: 'Clearer heading proposal',
    }))
    expect(repository.complete).not.toHaveBeenCalled()
  })

  it('preserves proposal completion failure semantics', async () => {
    for (const [completionCode, expectedCode] of [
      ['scope_violation', 'scope_violation'],
      ['invalid_design_document', 'invalid_model_output'],
      ['stale_document_version', 'stale_document_version'],
    ] as const) {
      const proposalRun = {
        ...job, mode: 'edit-selection' as const, delivery: 'proposal' as const,
        proposalStatus: 'preparing' as const, selectedNodeId: 'heading-1',
        id: job.generationRunId, status: 'queued', document: createValidDesignFixture(),
      }
      const repository = {
        getWorkerInput: vi.fn().mockResolvedValue(proposalRun),
        claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
        markRepairing: vi.fn(), complete: vi.fn(),
        completeProposal: vi.fn().mockResolvedValue({ accepted: false, code: completionCode }),
        fail: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'failed' }),
      }
      const processor = createGenerationProcessor({
        provider: createMockWorkerProvider([{ output: {
          summary: 'Clearer heading proposal',
          operations: [{ type: 'UPDATE_PROPS', nodeId: 'heading-1', patch: { text: 'Proposed heading' } }],
        } }]),
        repository,
      })

      await processor({ data: {
        generationRunId: job.generationRunId, projectId: job.projectId,
        workspaceId: job.workspaceId, userId: job.userId,
      } })
      expect(repository.fail).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
        errorCode: expectedCode,
      }))
    }
  })

  it('runs edit jobs with the edit policy and operations provider path', async () => {
    const editRun = {
      ...job,
      mode: 'edit-page' as const,
      id: job.generationRunId,
      status: 'queued',
      document: createValidDesignFixture(),
    }
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(editRun),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(),
      complete: vi.fn().mockResolvedValue({ accepted: true, run: { id: job.generationRunId, status: 'completed' } }),
      fail: vi.fn(),
    }
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: {
        summary: 'Improve heading',
        operations: [{ type: 'UPDATE_PROPS', nodeId: 'heading-1', patch: { text: 'Improved' } }],
      } }]),
      repository,
    })

    await expect(processor({ data: {
      generationRunId: job.generationRunId,
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      userId: job.userId,
    } })).resolves.toMatchObject({ status: 'completed' })
    expect(repository.complete).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      summary: 'Improve heading',
      document: expect.objectContaining({ version: 2 }),
    }))
  })

  it('enforces mode-specific aggregate token budgets', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({ ...job, id: job.generationRunId, status: 'queued', document: createValidDesignFixture() }),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(),
      complete: vi.fn(),
      fail: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'failed' }),
    }
    const provider = createMockWorkerProvider([{
      output: blueprint,
      usage: { inputTokens: 7, outputTokens: 6, totalTokens: 13 },
    }])
    const processor = createGenerationProcessor({
      provider,
      repository,
      generateMaxTotalTokens: 12,
    })

    await expect(processor({ data: {
      generationRunId: job.generationRunId,
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      userId: job.userId,
    } })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      errorCode: 'budget_exceeded',
      usage: { inputTokens: 7, outputTokens: 6, totalTokens: 13 },
      repairCount: 0,
    }))
    expect(repository.complete).not.toHaveBeenCalled()
  })

  it('claims, generates and atomically completes one job', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({ ...job, id: job.generationRunId, status: 'queued', document: createValidDesignFixture() }),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'repairing' }),
      complete: vi.fn().mockResolvedValue({ accepted: true, run: { id: job.generationRunId, status: 'completed' } }),
      fail: vi.fn(),
    }
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: blueprint }]),
      repository,
    })
    const metadataOnlyJob = {
      generationRunId: job.generationRunId,
      projectId: job.projectId,
      workspaceId: job.workspaceId,
      userId: job.userId,
    }

    await expect(processor({ data: metadataOnlyJob })).resolves.toMatchObject({ status: 'completed' })
    expect(repository.claim).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({ promptVersion: AI_PROMPT_VERSION }))
    expect(repository.complete).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      document: expect.objectContaining({ version: 2 }),
      summary: 'AI generated landing page',
    }))
    expect(repository.fail).not.toHaveBeenCalled()
  })

  it('marks exhausted output and stale completion as safe failures', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue({ ...job, id: job.generationRunId, status: 'queued', document: createValidDesignFixture() }),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'repairing' }),
      complete: vi.fn().mockResolvedValue({ accepted: false, code: 'stale_document_version' }),
      fail: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'failed' }),
    }
    const invalid = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: null }, { output: null }, { output: null }]),
      repository,
    })
    await expect(invalid({ data: { generationRunId: job.generationRunId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId } })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.markRepairing).not.toHaveBeenCalled()
    expect(repository.fail).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({ errorCode: 'invalid_model_output' }))

    repository.fail.mockClear()
    const stale = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: blueprint }]),
      repository,
    })
    await expect(stale({ data: { generationRunId: job.generationRunId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId } })).resolves.toMatchObject({ status: 'failed' })
    expect(repository.fail).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({ errorCode: 'stale_document_version' }))
  })

  it('maps missing and invalid completion outcomes without leaking repository details', async () => {
    const baseRepository = {
      getWorkerInput: vi.fn().mockResolvedValue({ ...job, id: job.generationRunId, status: 'queued', document: createValidDesignFixture() }),
      claim: vi.fn().mockResolvedValue({ id: job.generationRunId, status: 'running' }),
      markRepairing: vi.fn(),
      complete: vi.fn().mockResolvedValue({ accepted: false, code: 'invalid_design_document' }),
      fail: vi.fn().mockResolvedValue(null),
    }
    const processor = createGenerationProcessor({
      provider: createMockWorkerProvider([{ output: blueprint }]),
      repository: baseRepository,
      timeoutMs: 100,
      generateMaxRepairAttempts: 0,
      maxTransientRetries: 0,
    })
    await expect(processor({ data: { generationRunId: job.generationRunId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId } })).resolves.toMatchObject({ status: 'running' })
    expect(baseRepository.fail).toHaveBeenCalledWith(context, job.generationRunId, expect.objectContaining({
      errorCode: 'invalid_model_output',
    }))
    await expect(processor({ data: {
      generationRunId: job.generationRunId, projectId: job.projectId,
      workspaceId: job.workspaceId, userId: job.userId, unexpected: true,
    } as never })).rejects.toThrow('invalid_generation_job')
  })

  it('does not claim missing or already-claimed runs', async () => {
    const repository = {
      getWorkerInput: vi.fn().mockResolvedValue(null),
      claim: vi.fn(), markRepairing: vi.fn(), complete: vi.fn(), fail: vi.fn(),
    }
    const processor = createGenerationProcessor({ provider: createMockWorkerProvider([]), repository })
    await expect(processor({ data: { generationRunId: job.generationRunId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId } })).rejects.toThrow('generation_run_not_found')

    repository.getWorkerInput.mockResolvedValue({ ...job, id: job.generationRunId, document: createValidDesignFixture() })
    repository.claim.mockResolvedValue(null)
    await expect(processor({ data: { generationRunId: job.generationRunId, projectId: job.projectId, workspaceId: job.workspaceId, userId: job.userId } })).rejects.toThrow('generation_run_not_claimed')
  })
})
